// Code generated by https://github.com/gocomply/xsd2go; DO NOT EDIT.
// Models for http://ddex.net/xml/20121219/iso639a2
package iso639a2

import ()

// XSD ComplexType declarations

// XSD SimpleType declarations

type LanguageCode string

const LanguageCodeAa LanguageCode = "aa"

const LanguageCodeAb LanguageCode = "ab"

const LanguageCodeAe LanguageCode = "ae"

const LanguageCodeAf LanguageCode = "af"

const LanguageCodeAk LanguageCode = "ak"

const LanguageCodeAm LanguageCode = "am"

const LanguageCodeAn LanguageCode = "an"

const LanguageCodeAr LanguageCode = "ar"

const LanguageCodeAs LanguageCode = "as"

const LanguageCodeAv LanguageCode = "av"

const LanguageCodeAy LanguageCode = "ay"

const LanguageCodeAz LanguageCode = "az"

const LanguageCodeBa LanguageCode = "ba"

const LanguageCodeBe LanguageCode = "be"

const LanguageCodeBg LanguageCode = "bg"

const LanguageCodeBh LanguageCode = "bh"

const LanguageCodeBi LanguageCode = "bi"

const LanguageCodeBm LanguageCode = "bm"

const LanguageCodeBn LanguageCode = "bn"

const LanguageCodeBo LanguageCode = "bo"

const LanguageCodeBr LanguageCode = "br"

const LanguageCodeBs LanguageCode = "bs"

const LanguageCodeCa LanguageCode = "ca"

const LanguageCodeCe LanguageCode = "ce"

const LanguageCodeCh LanguageCode = "ch"

const LanguageCodeCo LanguageCode = "co"

const LanguageCodeCr LanguageCode = "cr"

const LanguageCodeCs LanguageCode = "cs"

const LanguageCodeCu LanguageCode = "cu"

const LanguageCodeCv LanguageCode = "cv"

const LanguageCodeCy LanguageCode = "cy"

const LanguageCodeDa LanguageCode = "da"

const LanguageCodeDe LanguageCode = "de"

const LanguageCodeDv LanguageCode = "dv"

const LanguageCodeDz LanguageCode = "dz"

const LanguageCodeEe LanguageCode = "ee"

const LanguageCodeEl LanguageCode = "el"

const LanguageCodeEn LanguageCode = "en"

const LanguageCodeEo LanguageCode = "eo"

const LanguageCodeEs LanguageCode = "es"

const LanguageCodeEt LanguageCode = "et"

const LanguageCodeEu LanguageCode = "eu"

const LanguageCodeFa LanguageCode = "fa"

const LanguageCodeFf LanguageCode = "ff"

const LanguageCodeFi LanguageCode = "fi"

const LanguageCodeFj LanguageCode = "fj"

const LanguageCodeFo LanguageCode = "fo"

const LanguageCodeFr LanguageCode = "fr"

const LanguageCodeFy LanguageCode = "fy"

const LanguageCodeGa LanguageCode = "ga"

const LanguageCodeGd LanguageCode = "gd"

const LanguageCodeGl LanguageCode = "gl"

const LanguageCodeGn LanguageCode = "gn"

const LanguageCodeGu LanguageCode = "gu"

const LanguageCodeGv LanguageCode = "gv"

const LanguageCodeHa LanguageCode = "ha"

const LanguageCodeHe LanguageCode = "he"

const LanguageCodeHi LanguageCode = "hi"

const LanguageCodeHo LanguageCode = "ho"

const LanguageCodeHr LanguageCode = "hr"

const LanguageCodeHt LanguageCode = "ht"

const LanguageCodeHu LanguageCode = "hu"

const LanguageCodeHy LanguageCode = "hy"

const LanguageCodeHz LanguageCode = "hz"

const LanguageCodeIa LanguageCode = "ia"

const LanguageCodeId LanguageCode = "id"

const LanguageCodeIe LanguageCode = "ie"

const LanguageCodeIg LanguageCode = "ig"

const LanguageCodeIi LanguageCode = "ii"

const LanguageCodeIk LanguageCode = "ik"

const LanguageCodeIo LanguageCode = "io"

const LanguageCodeIs LanguageCode = "is"

const LanguageCodeIt LanguageCode = "it"

const LanguageCodeIu LanguageCode = "iu"

const LanguageCodeJa LanguageCode = "ja"

const LanguageCodeJv LanguageCode = "jv"

const LanguageCodeKa LanguageCode = "ka"

const LanguageCodeKg LanguageCode = "kg"

const LanguageCodeKi LanguageCode = "ki"

const LanguageCodeKj LanguageCode = "kj"

const LanguageCodeKk LanguageCode = "kk"

const LanguageCodeKl LanguageCode = "kl"

const LanguageCodeKm LanguageCode = "km"

const LanguageCodeKn LanguageCode = "kn"

const LanguageCodeKo LanguageCode = "ko"

const LanguageCodeKr LanguageCode = "kr"

const LanguageCodeKs LanguageCode = "ks"

const LanguageCodeKu LanguageCode = "ku"

const LanguageCodeKv LanguageCode = "kv"

const LanguageCodeKw LanguageCode = "kw"

const LanguageCodeKy LanguageCode = "ky"

const LanguageCodeLa LanguageCode = "la"

const LanguageCodeLb LanguageCode = "lb"

const LanguageCodeLg LanguageCode = "lg"

const LanguageCodeLi LanguageCode = "li"

const LanguageCodeLn LanguageCode = "ln"

const LanguageCodeLo LanguageCode = "lo"

const LanguageCodeLt LanguageCode = "lt"

const LanguageCodeLu LanguageCode = "lu"

const LanguageCodeLv LanguageCode = "lv"

const LanguageCodeMg LanguageCode = "mg"

const LanguageCodeMh LanguageCode = "mh"

const LanguageCodeMi LanguageCode = "mi"

const LanguageCodeMk LanguageCode = "mk"

const LanguageCodeMl LanguageCode = "ml"

const LanguageCodeMn LanguageCode = "mn"

const LanguageCodeMo LanguageCode = "mo"

const LanguageCodeMr LanguageCode = "mr"

const LanguageCodeMs LanguageCode = "ms"

const LanguageCodeMt LanguageCode = "mt"

const LanguageCodeMy LanguageCode = "my"

const LanguageCodeNa LanguageCode = "na"

const LanguageCodeNb LanguageCode = "nb"

const LanguageCodeNd LanguageCode = "nd"

const LanguageCodeNe LanguageCode = "ne"

const LanguageCodeNg LanguageCode = "ng"

const LanguageCodeNl LanguageCode = "nl"

const LanguageCodeNn LanguageCode = "nn"

const LanguageCodeNo LanguageCode = "no"

const LanguageCodeNr LanguageCode = "nr"

const LanguageCodeNv LanguageCode = "nv"

const LanguageCodeNy LanguageCode = "ny"

const LanguageCodeOc LanguageCode = "oc"

const LanguageCodeOj LanguageCode = "oj"

const LanguageCodeOm LanguageCode = "om"

const LanguageCodeOr LanguageCode = "or"

const LanguageCodeOs LanguageCode = "os"

const LanguageCodePa LanguageCode = "pa"

const LanguageCodePi LanguageCode = "pi"

const LanguageCodePl LanguageCode = "pl"

const LanguageCodePs LanguageCode = "ps"

const LanguageCodePt LanguageCode = "pt"

const LanguageCodeQu LanguageCode = "qu"

const LanguageCodeRm LanguageCode = "rm"

const LanguageCodeRn LanguageCode = "rn"

const LanguageCodeRo LanguageCode = "ro"

const LanguageCodeRu LanguageCode = "ru"

const LanguageCodeRw LanguageCode = "rw"

const LanguageCodeSa LanguageCode = "sa"

const LanguageCodeSc LanguageCode = "sc"

const LanguageCodeSd LanguageCode = "sd"

const LanguageCodeSe LanguageCode = "se"

const LanguageCodeSg LanguageCode = "sg"

const LanguageCodeSi LanguageCode = "si"

const LanguageCodeSk LanguageCode = "sk"

const LanguageCodeSl LanguageCode = "sl"

const LanguageCodeSm LanguageCode = "sm"

const LanguageCodeSn LanguageCode = "sn"

const LanguageCodeSo LanguageCode = "so"

const LanguageCodeSq LanguageCode = "sq"

const LanguageCodeSr LanguageCode = "sr"

const LanguageCodeSs LanguageCode = "ss"

const LanguageCodeSt LanguageCode = "st"

const LanguageCodeSu LanguageCode = "su"

const LanguageCodeSv LanguageCode = "sv"

const LanguageCodeSw LanguageCode = "sw"

const LanguageCodeTa LanguageCode = "ta"

const LanguageCodeTe LanguageCode = "te"

const LanguageCodeTg LanguageCode = "tg"

const LanguageCodeTh LanguageCode = "th"

const LanguageCodeTi LanguageCode = "ti"

const LanguageCodeTk LanguageCode = "tk"

const LanguageCodeTl LanguageCode = "tl"

const LanguageCodeTn LanguageCode = "tn"

const LanguageCodeTo LanguageCode = "to"

const LanguageCodeTr LanguageCode = "tr"

const LanguageCodeTs LanguageCode = "ts"

const LanguageCodeTt LanguageCode = "tt"

const LanguageCodeTw LanguageCode = "tw"

const LanguageCodeTy LanguageCode = "ty"

const LanguageCodeUg LanguageCode = "ug"

const LanguageCodeUk LanguageCode = "uk"

const LanguageCodeUr LanguageCode = "ur"

const LanguageCodeUz LanguageCode = "uz"

const LanguageCodeVe LanguageCode = "ve"

const LanguageCodeVi LanguageCode = "vi"

const LanguageCodeVo LanguageCode = "vo"

const LanguageCodeWa LanguageCode = "wa"

const LanguageCodeWo LanguageCode = "wo"

const LanguageCodeXh LanguageCode = "xh"

const LanguageCodeYi LanguageCode = "yi"

const LanguageCodeYo LanguageCode = "yo"

const LanguageCodeZa LanguageCode = "za"

const LanguageCodeZh LanguageCode = "zh"

const LanguageCodeZu LanguageCode = "zu"
