// Code generated by https://github.com/gocomply/xsd2go; DO NOT EDIT.
// Models for http://ddex.net/xml/20121219/ddex
package ddex

import ()

// XSD ComplexType declarations

// XSD SimpleType declarations

type AccessLimitation string

const AccessLimitationNolimitation AccessLimitation = "NoLimitation"

const AccessLimitationPrivateaccessonly AccessLimitation = "PrivateAccessOnly"

type AdministratingRecordCompanyRole string

const AdministratingRecordCompanyRoleDesignateddsrmessagerecipient AdministratingRecordCompanyRole = "DesignatedDsrMessageRecipient"

const AdministratingRecordCompanyRoleRightsadministrator AdministratingRecordCompanyRole = "RightsAdministrator"

const AdministratingRecordCompanyRoleRoyaltyadministrator AdministratingRecordCompanyRole = "RoyaltyAdministrator"

const AdministratingRecordCompanyRoleUnknown AdministratingRecordCompanyRole = "Unknown"

const AdministratingRecordCompanyRoleUserdefined AdministratingRecordCompanyRole = "UserDefined"

type ArtistRole string

const ArtistRoleActor ArtistRole = "Actor"

const ArtistRoleAdapter ArtistRole = "Adapter"

const ArtistRoleArchitect ArtistRole = "Architect"

const ArtistRoleArranger ArtistRole = "Arranger"

const ArtistRoleArtist ArtistRole = "Artist"

const ArtistRoleAssociatedperformer ArtistRole = "AssociatedPerformer"

const ArtistRoleAuthor ArtistRole = "Author"

const ArtistRoleBand ArtistRole = "Band"

const ArtistRoleCartoonist ArtistRole = "Cartoonist"

const ArtistRoleChoir ArtistRole = "Choir"

const ArtistRoleChoreographer ArtistRole = "Choreographer"

const ArtistRoleComposer ArtistRole = "Composer"

const ArtistRoleComposerlyricist ArtistRole = "ComposerLyricist"

const ArtistRoleComputergraphiccreator ArtistRole = "ComputerGraphicCreator"

const ArtistRoleConductor ArtistRole = "Conductor"

const ArtistRoleContributor ArtistRole = "Contributor"

const ArtistRoleDancer ArtistRole = "Dancer"

const ArtistRoleDesigner ArtistRole = "Designer"

const ArtistRoleDirector ArtistRole = "Director"

const ArtistRoleEnsemble ArtistRole = "Ensemble"

const ArtistRoleFeaturedartist ArtistRole = "FeaturedArtist"

const ArtistRoleFilmdirector ArtistRole = "FilmDirector"

const ArtistRoleGraphicartist ArtistRole = "GraphicArtist"

const ArtistRoleGraphicdesigner ArtistRole = "GraphicDesigner"

const ArtistRoleJournalist ArtistRole = "Journalist"

const ArtistRoleLibrettist ArtistRole = "Librettist"

const ArtistRoleLyricist ArtistRole = "Lyricist"

const ArtistRoleMainartist ArtistRole = "MainArtist"

const ArtistRoleMusicpublisher ArtistRole = "MusicPublisher"

const ArtistRoleNonlyricauthor ArtistRole = "NonLyricAuthor"

const ArtistRoleOrchestra ArtistRole = "Orchestra"

const ArtistRoleOriginalpublisher ArtistRole = "OriginalPublisher"

const ArtistRolePainter ArtistRole = "Painter"

const ArtistRolePhotographer ArtistRole = "Photographer"

const ArtistRolePhotographydirector ArtistRole = "PhotographyDirector"

const ArtistRolePlaywright ArtistRole = "Playwright"

const ArtistRolePrimarymusician ArtistRole = "PrimaryMusician"

const ArtistRoleProducer ArtistRole = "Producer"

const ArtistRoleProgrammer ArtistRole = "Programmer"

const ArtistRoleScreenplayauthor ArtistRole = "ScreenplayAuthor"

const ArtistRoleSoloist ArtistRole = "Soloist"

const ArtistRoleStudiomusician ArtistRole = "StudioMusician"

const ArtistRoleStudiopersonnel ArtistRole = "StudioPersonnel"

const ArtistRoleSubarranger ArtistRole = "SubArranger"

const ArtistRoleSubpublisher ArtistRole = "SubPublisher"

const ArtistRoleSubstitutedpublisher ArtistRole = "SubstitutedPublisher"

const ArtistRoleTranslator ArtistRole = "Translator"

const ArtistRoleUnknown ArtistRole = "Unknown"

const ArtistRoleUserdefined ArtistRole = "UserDefined"

type AudioCodecType string

const AudioCodecTypeAac AudioCodecType = "AAC"

const AudioCodecTypeAdpcm AudioCodecType = "ADPCM"

const AudioCodecTypeAlaw AudioCodecType = "ALaw"

const AudioCodecTypeAmrNb AudioCodecType = "AMR-NB"

const AudioCodecTypeAmrWb AudioCodecType = "AMR-WB"

const AudioCodecTypeFlac AudioCodecType = "FLAC"

const AudioCodecTypeMp2 AudioCodecType = "MP2"

const AudioCodecTypeMp3 AudioCodecType = "MP3"

const AudioCodecTypeMulaw AudioCodecType = "MuLaw"

const AudioCodecTypePcm AudioCodecType = "PCM"

const AudioCodecTypePdm AudioCodecType = "PDM"

const AudioCodecTypeQcelp AudioCodecType = "QCELP"

const AudioCodecTypeRealaudio AudioCodecType = "RealAudio"

const AudioCodecTypeShockwave AudioCodecType = "Shockwave"

const AudioCodecTypeUnknown AudioCodecType = "Unknown"

const AudioCodecTypeUserdefined AudioCodecType = "UserDefined"

const AudioCodecTypeVorbis AudioCodecType = "Vorbis"

const AudioCodecTypeWma AudioCodecType = "WMA"

type CalculationType string

type CarrierType string

const CarrierType12inchdiscosingleremix CarrierType = "12InchDiscoSingleRemix"

const CarrierType33rpm10Inchlp CarrierType = "33rpm10InchLP"

const CarrierType33rpm10Inchsingle CarrierType = "33rpm10InchSingle"

const CarrierType33rpm12Inchlp CarrierType = "33rpm12InchLP"

const CarrierType33rpm12Inchlp20Tracks CarrierType = "33rpm12InchLp20Tracks"

const CarrierType33rpm12Inchmaxisingle CarrierType = "33rpm12InchMaxiSingle"

const CarrierType33rpm12Inchsingle CarrierType = "33rpm12InchSingle"

const CarrierType33rpm7Inchlp CarrierType = "33rpm7InchLP"

const CarrierType33rpm7Inchsingle CarrierType = "33rpm7InchSingle"

const CarrierType45rpm10Inchlp CarrierType = "45rpm10InchLP"

const CarrierType45rpm10Inchmaxisingle CarrierType = "45rpm10InchMaxiSingle"

const CarrierType45rpm10Inchsingle CarrierType = "45rpm10InchSingle"

const CarrierType45rpm12Inchlp CarrierType = "45rpm12InchLP"

const CarrierType45rpm12Inchmaxisingle CarrierType = "45rpm12InchMaxiSingle"

const CarrierType45rpm12Inchsingle CarrierType = "45rpm12InchSingle"

const CarrierType45rpm7Inchep CarrierType = "45rpm7InchEP"

const CarrierType45rpm7Inchsingle CarrierType = "45rpm7InchSingle"

const CarrierType7inchmaxisingleremix CarrierType = "7InchMaxiSingleRemix"

const CarrierTypeBluray CarrierType = "BluRay"

const CarrierTypeCd CarrierType = "CD"

const CarrierTypeCdcompilation CarrierType = "CdCompilation"

const CarrierTypeCdep CarrierType = "CdEp"

const CarrierTypeCdepenhanced CarrierType = "CdEpEnhanced"

const CarrierTypeCdextracompilation CarrierType = "CdExtraCompilation"

const CarrierTypeCdextraep CarrierType = "CdExtraEP"

const CarrierTypeCdextralp CarrierType = "CdExtraLP"

const CarrierTypeCdextramaxiremix CarrierType = "CdExtraMaxiRemix"

const CarrierTypeCdextramaxisingle CarrierType = "CdExtraMaxiSingle"

const CarrierTypeCdextrasingle CarrierType = "CdExtraSingle"

const CarrierTypeCdextrasingle2Tracks CarrierType = "CdExtraSingle2Tracks"

const CarrierTypeCdlp CarrierType = "CdLp"

const CarrierTypeCdlp5Inch CarrierType = "CdLp5Inch"

const CarrierTypeCdlpenhanced CarrierType = "CdLpEnhanced"

const CarrierTypeCdlppluscdvideo CarrierType = "CdLpPlusCdVideo"

const CarrierTypeCdlpplusdvdaudio CarrierType = "CdLpPlusDvdAudio"

const CarrierTypeCdlpplusdvdvideo CarrierType = "CdLpPlusDvdVideo"

const CarrierTypeCdlpplusweb CarrierType = "CdLpPlusWeb"

const CarrierTypeCdmaxisingle CarrierType = "CdMaxiSingle"

const CarrierTypeCdmaxisingle3Inch CarrierType = "CdMaxiSingle3Inch"

const CarrierTypeCdmaxisingleenhanced CarrierType = "CdMaxiSingleEnhanced"

const CarrierTypeCdmaxisingleremix CarrierType = "CdMaxiSingleRemix"

const CarrierTypeCdpluscdbonus CarrierType = "CdPlusCdBonus"

const CarrierTypeCdplusdvdbonus CarrierType = "CdPlusDvdBonus"

const CarrierTypeCdrom CarrierType = "CdRom"

const CarrierTypeCdsingle CarrierType = "CdSingle"

const CarrierTypeCdsingle3Inch CarrierType = "CdSingle3Inch"

const CarrierTypeCdsingle5Inch CarrierType = "CdSingle5Inch"

const CarrierTypeCdvideo5Lpntsc CarrierType = "CdVideo5LpNTSC"

const CarrierTypeCdvideo5Lppal CarrierType = "CdVideo5LpPAL"

const CarrierTypeCdvideoaudiocompatible CarrierType = "CdVideoAudioCompatible"

const CarrierTypeCombipack CarrierType = "CombiPack"

const CarrierTypeDcc CarrierType = "DCC"

const CarrierTypeDcccompilation CarrierType = "DccCompilation"

const CarrierTypeDualdisc CarrierType = "DualDisc"

const CarrierTypeDvd CarrierType = "DVD"

const CarrierTypeDvdaudio CarrierType = "DvdAudio"

const CarrierTypeDvdaudio5Maxisingle CarrierType = "DvdAudio5MaxiSingle"

const CarrierTypeDvdaudiolp CarrierType = "DvdAudioLP"

const CarrierTypeDvdaudiosingle CarrierType = "DvdAudioSingle"

const CarrierTypeDvdrom CarrierType = "DvdRom"

const CarrierTypeDvdsingle CarrierType = "DvdSingle"

const CarrierTypeDvdvideo CarrierType = "DvdVideo"

const CarrierTypeDvdvideo5Maxisinglentsc CarrierType = "DvdVideo5MaxiSingleNTSC"

const CarrierTypeDvdvideo5Maxisinglepal CarrierType = "DvdVideo5MaxiSinglePAL"

const CarrierTypeDvdvideo5Singlentsc CarrierType = "DvdVideo5SingleNTSC"

const CarrierTypeDvdvideo5Singlepal CarrierType = "DvdVideo5SinglePAL"

const CarrierTypeDvdvideolpntsc CarrierType = "DvdVideoLpNTSC"

const CarrierTypeDvdvideolppal CarrierType = "DvdVideoLpPAL"

const CarrierTypeDvdvideolppluscdlporcdsingle CarrierType = "DvdVideoLpPlusCdLpOrCdSingle"

const CarrierTypeFanpack CarrierType = "FanPack"

const CarrierTypeHddvdvideolp CarrierType = "HdDvdVideoLp"

const CarrierTypeLaserdisclp12Inchntsc CarrierType = "LaserDiscLp12InchNTSC"

const CarrierTypeLpcompidenticaltocdcomp CarrierType = "LpCompIdenticalToCdComp"

const CarrierTypeLpcompilation CarrierType = "LpCompilation"

const CarrierTypeLpidenticaltocd CarrierType = "LpIdenticalToCD"

const CarrierTypeMc CarrierType = "MC"

const CarrierTypeMccompidenticaltocdcomp CarrierType = "McCompIdenticalToCdComp"

const CarrierTypeMccompilation CarrierType = "McCompilation"

const CarrierTypeMcdoublelp CarrierType = "McDoubleLP"

const CarrierTypeMcep CarrierType = "McEP"

const CarrierTypeMcidenticaltocd CarrierType = "McIdenticalToCD"

const CarrierTypeMclp CarrierType = "McLP"

const CarrierTypeMcmaxisingle CarrierType = "McMaxiSingle"

const CarrierTypeMcremix CarrierType = "McRemix"

const CarrierTypeMcsingle CarrierType = "McSingle"

const CarrierTypeMcsingleidenticaltocds CarrierType = "McSingleIdenticalToCDS"

const CarrierTypeMemorydeviceaudiolp CarrierType = "MemoryDeviceAudioLP"

const CarrierTypeMemorydevicemixlp CarrierType = "MemoryDeviceMixLP"

const CarrierTypeMemorydevicevideolp CarrierType = "MemoryDeviceVideoLP"

const CarrierTypeMerchandise CarrierType = "Merchandise"

const CarrierTypeMinidisc CarrierType = "MiniDisc"

const CarrierTypeMinidisccompilation CarrierType = "MiniDiscCompilation"

const CarrierTypeMinidiscep CarrierType = "MiniDiscEP"

const CarrierTypeMinidiscmaxiremix CarrierType = "MiniDiscMaxiRemix"

const CarrierTypeMinidiscsinglemaxisingle CarrierType = "MiniDiscSingleMaxiSingle"

const CarrierTypePrepaidcard CarrierType = "PrePaidCard"

const CarrierTypeSacd CarrierType = "SACD"

const CarrierTypeSacdcompilation CarrierType = "SacdCompilation"

const CarrierTypeSacdlpstereo CarrierType = "SacdLpStereo"

const CarrierTypeSacdlpstereocdaudio CarrierType = "SacdLpStereoCdAudio"

const CarrierTypeSacdlpstereosurround CarrierType = "SacdLpStereoSurround"

const CarrierTypeSacdlpstereosurroundcdaudio CarrierType = "SacdLpStereoSurroundCdAudio"

const CarrierTypeSacdlpsurroundcdaudio CarrierType = "SacdLpSurroundCdAudio"

const CarrierTypeSacdplusdvdvideo CarrierType = "SacdPlusDvdVideo"

const CarrierTypeVhsntsc CarrierType = "VhsNTSC"

const CarrierTypeVhspal CarrierType = "VhsPAL"

const CarrierTypeVhspluscdlp CarrierType = "VhsPlusCdLp"

const CarrierTypeVhssecam CarrierType = "VhsSECAM"

type CdProtectionType string

const CdProtectionTypeCds100 CdProtectionType = "CDS100"

const CdProtectionTypeCds200 CdProtectionType = "CDS200"

const CdProtectionTypeCds300 CdProtectionType = "CDS300"

const CdProtectionTypeKey2Audio CdProtectionType = "Key2Audio"

const CdProtectionTypeMediamaxcd3 CdProtectionType = "MediaMaxCD3"

const CdProtectionTypeNotprotected CdProtectionType = "NotProtected"

const CdProtectionTypeUnknown CdProtectionType = "Unknown"

const CdProtectionTypeUserdefined CdProtectionType = "UserDefined"

type CodingType string

const CodingTypeLossless CodingType = "Lossless"

const CodingTypeLossy CodingType = "Lossy"

type CollectionType string

const CollectionTypeAudiochapter CollectionType = "AudioChapter"

const CollectionTypeEpisode CollectionType = "Episode"

const CollectionTypeMedleysegment CollectionType = "MedleySegment"

const CollectionTypePotpourrisegment CollectionType = "PotpourriSegment"

const CollectionTypeSeason CollectionType = "Season"

const CollectionTypeSeries CollectionType = "Series"

const CollectionTypeVideochapter CollectionType = "VideoChapter"

type CommercialModelType string

const CommercialModelTypeAdvertisementsupportedmodel CommercialModelType = "AdvertisementSupportedModel"

const CommercialModelTypeAspercontract CommercialModelType = "AsPerContract"

const CommercialModelTypeDevicefeemodel CommercialModelType = "DeviceFeeModel"

const CommercialModelTypeFreeofchargemodel CommercialModelType = "FreeOfChargeModel"

const CommercialModelTypePayasyougomodel CommercialModelType = "PayAsYouGoModel"

const CommercialModelTypePerformanceroyaltiesmodel CommercialModelType = "PerformanceRoyaltiesModel"

const CommercialModelTypeRightsclaimmodel CommercialModelType = "RightsClaimModel"

const CommercialModelTypeSubscriptionmodel CommercialModelType = "SubscriptionModel"

const CommercialModelTypeUnknown CommercialModelType = "Unknown"

const CommercialModelTypeUserdefined CommercialModelType = "UserDefined"

type CompilationType string

const CompilationTypeInternalcompilation CompilationType = "InternalCompilation"

const CompilationTypeNoninternalcompilation CompilationType = "NonInternalCompilation"

const CompilationTypeNotcompiled CompilationType = "NotCompiled"

type ContainerFormat string

const ContainerFormatAiff ContainerFormat = "AIFF"

const ContainerFormatAvi ContainerFormat = "AVI"

const ContainerFormatMp4 ContainerFormat = "MP4"

const ContainerFormatOgg ContainerFormat = "Ogg"

const ContainerFormatQuicktime ContainerFormat = "QuickTime"

const ContainerFormatRealmedia ContainerFormat = "RealMedia"

const ContainerFormatRmf ContainerFormat = "RMF"

const ContainerFormatUserdefined ContainerFormat = "UserDefined"

const ContainerFormatWav ContainerFormat = "WAV"

type CreationType string

const CreationTypeMusicalwork CreationType = "MusicalWork"

const CreationTypeRelease CreationType = "Release"

const CreationTypeResource CreationType = "Resource"

type CueOrigin string

const CueOriginLibrarymusic CueOrigin = "LibraryMusic"

const CueOriginPreexistingmusic CueOrigin = "PreexistingMusic"

const CueOriginSpeciallycommissionedmusic CueOrigin = "SpeciallyCommissionedMusic"

const CueOriginUnknown CueOrigin = "Unknown"

const CueOriginUserdefined CueOrigin = "UserDefined"

type CueSheetType string

const CueSheetTypeAveragecuesheet CueSheetType = "AverageCueSheet"

const CueSheetTypeCompositecuesheet CueSheetType = "CompositeCueSheet"

const CueSheetTypeStandardcuesheet CueSheetType = "StandardCueSheet"

const CueSheetTypeSummarisedcuesheet CueSheetType = "SummarisedCueSheet"

const CueSheetTypeSurrogatecuesheet CueSheetType = "SurrogateCueSheet"

type CueUseType string

const CueUseTypeAudiologo CueUseType = "AudioLogo"

const CueUseTypeBackground CueUseType = "Background"

const CueUseTypeBumper CueUseType = "Bumper"

const CueUseTypeEssentialpart CueUseType = "EssentialPart"

const CueUseTypeFilmtheme CueUseType = "FilmTheme"

const CueUseTypeIndistinguishablebackground CueUseType = "IndistinguishableBackground"

const CueUseTypeOnscreenmusic CueUseType = "OnScreenMusic"

const CueUseTypeRolledupcue CueUseType = "RolledUpCue"

const CueUseTypeTheme CueUseType = "Theme"

const CueUseTypeUserdefined CueUseType = "UserDefined"

type DataMismatchResponseType string

const DataMismatchResponseTypeAdditionalinformationonly DataMismatchResponseType = "AdditionalInformationOnly"

const DataMismatchResponseTypeDatamismatchconfirmation DataMismatchResponseType = "DataMismatchConfirmation"

const DataMismatchResponseTypeDatamismatchoutofscope DataMismatchResponseType = "DataMismatchOutOfScope"

const DataMismatchResponseTypeDatamismatchraisedcommercialdispute DataMismatchResponseType = "DataMismatchRaisedCommercialDispute"

const DataMismatchResponseTypeNoreaction DataMismatchResponseType = "NoReaction"

const DataMismatchResponseTypeUserdefined DataMismatchResponseType = "UserDefined"

type DataMismatchStatus string

const DataMismatchStatusAdditionalinformationonly DataMismatchStatus = "AdditionalInformationOnly"

const DataMismatchStatusCorrected DataMismatchStatus = "Corrected"

const DataMismatchStatusFatal DataMismatchStatus = "Fatal"

const DataMismatchStatusNotcorrected DataMismatchStatus = "NotCorrected"

const DataMismatchStatusUserdefined DataMismatchStatus = "UserDefined"

type DataMismatchType string

const DataMismatchTypeAdditionalinformationonly DataMismatchType = "AdditionalInformationOnly"

const DataMismatchTypeChoreographyconflict DataMismatchType = "ChoreographyConflict"

const DataMismatchTypeContradictorydata DataMismatchType = "ContradictoryData"

const DataMismatchTypeDuplicateddata DataMismatchType = "DuplicatedData"

const DataMismatchTypeIdentifiersyntaxmismatch DataMismatchType = "IdentifierSyntaxMismatch"

const DataMismatchTypeMathematicalinconsistency DataMismatchType = "MathematicalInconsistency"

const DataMismatchTypeMissingcontractuallymandatoryinformation DataMismatchType = "MissingContractuallyMandatoryInformation"

const DataMismatchTypeMissingmandatoryinformation DataMismatchType = "MissingMandatoryInformation"

const DataMismatchTypeMissingreferencedmusicalworkinformation DataMismatchType = "MissingReferencedMusicalWorkInformation"

const DataMismatchTypeMissingreferencedreleaseinformation DataMismatchType = "MissingReferencedReleaseInformation"

const DataMismatchTypeMissingreferencedresourceinformation DataMismatchType = "MissingReferencedResourceInformation"

const DataMismatchTypeMissingreferencedtechnicalresourcedetailinformation DataMismatchType = "MissingReferencedTechnicalResourceDetailInformation"

const DataMismatchTypeMissingresourcefile DataMismatchType = "MissingResourceFile"

const DataMismatchTypeTypographicmismatch DataMismatchType = "TypographicMismatch"

const DataMismatchTypeUnexpectedallowedvalue DataMismatchType = "UnexpectedAllowedValue"

const DataMismatchTypeUnexpectedmessageintermediary DataMismatchType = "UnexpectedMessageIntermediary"

const DataMismatchTypeUnexpectedmessagerecipient DataMismatchType = "UnexpectedMessageRecipient"

const DataMismatchTypeUnexpectedmessagesender DataMismatchType = "UnexpectedMessageSender"

const DataMismatchTypeUserdefined DataMismatchType = "UserDefined"

const DataMismatchTypeXmlformaterror DataMismatchType = "XmlFormatError"

const DataMismatchTypeXmlrangeerror DataMismatchType = "XmlRangeError"

type DeductionRateType string

const DeductionRateTypePennyrate DeductionRateType = "PennyRate"

const DeductionRateTypePercentagerate DeductionRateType = "PercentageRate"

const DeductionRateTypeUserdefined DeductionRateType = "UserDefined"

type DeliveryActionType string

const DeliveryActionTypeChangedeliverylimits DeliveryActionType = "ChangeDeliveryLimits"

const DeliveryActionTypeRestartdeliverywithlimits DeliveryActionType = "RestartDeliveryWithLimits"

const DeliveryActionTypeRestartdeliverywithpreviouslimits DeliveryActionType = "RestartDeliveryWithPreviousLimits"

const DeliveryActionTypeStopdelivery DeliveryActionType = "StopDelivery"

type DeliveryMessageType string

const DeliveryMessageTypeNewreleasemessage DeliveryMessageType = "NewReleaseMessage"

const DeliveryMessageTypeNonddexmessage DeliveryMessageType = "NonDdexMessage"

const DeliveryMessageTypeUnknown DeliveryMessageType = "Unknown"

type DeprecatedCurrencyCode string

const DeprecatedCurrencyCodeCyp DeprecatedCurrencyCode = "CYP"

const DeprecatedCurrencyCodeEek DeprecatedCurrencyCode = "EEK"

const DeprecatedCurrencyCodeMtl DeprecatedCurrencyCode = "MTL"

const DeprecatedCurrencyCodeRol DeprecatedCurrencyCode = "ROL"

const DeprecatedCurrencyCodeSit DeprecatedCurrencyCode = "SIT"

const DeprecatedCurrencyCodeSkk DeprecatedCurrencyCode = "SKK"

type DigitizationMode string

const DigitizationModeAad DigitizationMode = "AAD"

const DigitizationModeAdd DigitizationMode = "ADD"

const DigitizationModeDdd DigitizationMode = "DDD"

const DigitizationModeUnknown DigitizationMode = "Unknown"

type DistributionChannelType string

const DistributionChannelTypeAspercontract DistributionChannelType = "AsPerContract"

const DistributionChannelTypeBroadcast DistributionChannelType = "Broadcast"

const DistributionChannelTypeCable DistributionChannelType = "Cable"

const DistributionChannelTypeInternet DistributionChannelType = "Internet"

const DistributionChannelTypeInternetandmobile DistributionChannelType = "InternetAndMobile"

const DistributionChannelTypeIptv DistributionChannelType = "IPTV"

const DistributionChannelTypeMobiletelephone DistributionChannelType = "MobileTelephone"

const DistributionChannelTypeNarrowcast DistributionChannelType = "Narrowcast"

const DistributionChannelTypeOndemandstream DistributionChannelType = "OnDemandStream"

const DistributionChannelTypePeertopeer DistributionChannelType = "PeerToPeer"

const DistributionChannelTypePhysical DistributionChannelType = "Physical"

const DistributionChannelTypeSatellite DistributionChannelType = "Satellite"

const DistributionChannelTypeSimulcast DistributionChannelType = "Simulcast"

const DistributionChannelTypeUnknown DistributionChannelType = "Unknown"

const DistributionChannelTypeUserdefined DistributionChannelType = "UserDefined"

const DistributionChannelTypeWebcast DistributionChannelType = "Webcast"

type DrmEnforcementType string

const DrmEnforcementTypeDrmenforced DrmEnforcementType = "DrmEnforced"

const DrmEnforcementTypeNotdrmenforced DrmEnforcementType = "NotDrmEnforced"

type DrmPlatformType string

const DrmPlatformType3day DrmPlatformType = "3Day"

const DrmPlatformTypeFairplay DrmPlatformType = "Fairplay"

const DrmPlatformTypeOma DrmPlatformType = "OMA"

const DrmPlatformTypeUnknown DrmPlatformType = "Unknown"

const DrmPlatformTypeUserdefined DrmPlatformType = "UserDefined"

const DrmPlatformTypeWindowsmediadrm DrmPlatformType = "WindowsMediaDRM"

type DsrMessageType string

const DsrMessageTypeSalesreporttorecordcompanymessage DsrMessageType = "SalesReportToRecordCompanyMessage"

const DsrMessageTypeSalesreporttosocietymessage DsrMessageType = "SalesReportToSocietyMessage"

type ErnMessageType string

const ErnMessageTypeNewreleasemessage ErnMessageType = "NewReleaseMessage"

type ExpressionType string

const ExpressionTypeInformative ExpressionType = "Informative"

const ExpressionTypeInstructive ExpressionType = "Instructive"

type ExternallyLinkedResourceType string

const ExternallyLinkedResourceTypeAdditionalmetadata ExternallyLinkedResourceType = "AdditionalMetadata"

const ExternallyLinkedResourceTypeLogo ExternallyLinkedResourceType = "Logo"

const ExternallyLinkedResourceTypePromotionalimage ExternallyLinkedResourceType = "PromotionalImage"

const ExternallyLinkedResourceTypePromotionalinformation ExternallyLinkedResourceType = "PromotionalInformation"

const ExternallyLinkedResourceTypePromotionalitem ExternallyLinkedResourceType = "PromotionalItem"

const ExternallyLinkedResourceTypeUnknown ExternallyLinkedResourceType = "Unknown"

const ExternallyLinkedResourceTypeUserdefined ExternallyLinkedResourceType = "UserDefined"

type FileStatus string

const FileStatusFilemissing FileStatus = "FileMissing"

const FileStatusFileok FileStatus = "FileOK"

const FileStatusHashsumwrong FileStatus = "HashSumWrong"

const FileStatusSignaturewrong FileStatus = "SignatureWrong"

type FingerprintAlgorithmType string

const FingerprintAlgorithmTypeUserdefined FingerprintAlgorithmType = "UserDefined"

type GoverningAgreementType string

const GoverningAgreementTypeUserdefined GoverningAgreementType = "UserDefined"

type HashSumAlgorithmType string

const HashSumAlgorithmTypeMd4 HashSumAlgorithmType = "MD4"

const HashSumAlgorithmTypeMd5 HashSumAlgorithmType = "MD5"

const HashSumAlgorithmTypeSha HashSumAlgorithmType = "SHA"

const HashSumAlgorithmTypeSha1 HashSumAlgorithmType = "SHA1"

const HashSumAlgorithmTypeUserdefined HashSumAlgorithmType = "UserDefined"

type ImageCodecType string

const ImageCodecTypeGif ImageCodecType = "GIF"

const ImageCodecTypeJpeg ImageCodecType = "JPEG"

const ImageCodecTypeJpeg2000 ImageCodecType = "JPEG2000"

const ImageCodecTypePng ImageCodecType = "PNG"

const ImageCodecTypeTiff ImageCodecType = "TIFF"

const ImageCodecTypeUnknown ImageCodecType = "Unknown"

const ImageCodecTypeUserdefined ImageCodecType = "UserDefined"

type ImageType string

const ImageTypeBackcoverimage ImageType = "BackCoverImage"

const ImageTypeBookletbackimage ImageType = "BookletBackImage"

const ImageTypeBookletfrontimage ImageType = "BookletFrontImage"

const ImageTypeDocumentimage ImageType = "DocumentImage"

const ImageTypeFrontcoverimage ImageType = "FrontCoverImage"

const ImageTypeIcon ImageType = "Icon"

const ImageTypeLogo ImageType = "Logo"

const ImageTypePhotograph ImageType = "Photograph"

const ImageTypePoster ImageType = "Poster"

const ImageTypeTrayimage ImageType = "TrayImage"

const ImageTypeUnknown ImageType = "Unknown"

const ImageTypeUserdefined ImageType = "UserDefined"

const ImageTypeVideoscreencapture ImageType = "VideoScreenCapture"

const ImageTypeWallpaper ImageType = "Wallpaper"

type InvoiceAvailabilityStatus string

const InvoiceAvailabilityStatusInvoiceavailable InvoiceAvailabilityStatus = "InvoiceAvailable"

const InvoiceAvailabilityStatusInvoicenotavailable InvoiceAvailabilityStatus = "InvoiceNotAvailable"

type LicenseOrClaimRefusalReason string

const LicenseOrClaimRefusalReasonAgreementofadditionalprovisionsrequired LicenseOrClaimRefusalReason = "AgreementOfAdditionalProvisionsRequired"

const LicenseOrClaimRefusalReasonCorrectionofadvancepaymentrequired LicenseOrClaimRefusalReason = "CorrectionOfAdvancePaymentRequired"

const LicenseOrClaimRefusalReasonCorrectionofguaranteerequired LicenseOrClaimRefusalReason = "CorrectionOfGuaranteeRequired"

const LicenseOrClaimRefusalReasonCorrectionoflicenseerequired LicenseOrClaimRefusalReason = "CorrectionOfLicenseeRequired"

const LicenseOrClaimRefusalReasonCorrectionofmostfavorednationclauserequired LicenseOrClaimRefusalReason = "CorrectionOfMostFavoredNationClauseRequired"

const LicenseOrClaimRefusalReasonCorrectionofnumberofresourcesrequired LicenseOrClaimRefusalReason = "CorrectionOfNumberOfResourcesRequired"

const LicenseOrClaimRefusalReasonCorrectionofplayingtimerequired LicenseOrClaimRefusalReason = "CorrectionOfPlayingTimeRequired"

const LicenseOrClaimRefusalReasonCorrectionofpublisherinformationrequired LicenseOrClaimRefusalReason = "CorrectionOfPublisherInformationRequired"

const LicenseOrClaimRefusalReasonCorrectionofpublisherpercentagerequired LicenseOrClaimRefusalReason = "CorrectionOfPublisherPercentageRequired"

const LicenseOrClaimRefusalReasonCorrectionofraterequired LicenseOrClaimRefusalReason = "CorrectionOfRateRequired"

const LicenseOrClaimRefusalReasonCorrectionofreleasecreatorinformationrequired LicenseOrClaimRefusalReason = "CorrectionOfReleaseCreatorInformationRequired"

const LicenseOrClaimRefusalReasonCorrectionofreleasedaterequired LicenseOrClaimRefusalReason = "CorrectionOfReleaseDateRequired"

const LicenseOrClaimRefusalReasonCorrectionofreleasetitlerequired LicenseOrClaimRefusalReason = "CorrectionOfReleaseTitleRequired"

const LicenseOrClaimRefusalReasonCorrectionofworkcontributorrequired LicenseOrClaimRefusalReason = "CorrectionOfWorkContributorRequired"

const LicenseOrClaimRefusalReasonCorrectionofworktitlerequired LicenseOrClaimRefusalReason = "CorrectionOfWorkTitleRequired"

const LicenseOrClaimRefusalReasonDealexpired LicenseOrClaimRefusalReason = "DealExpired"

const LicenseOrClaimRefusalReasonDifferentwork LicenseOrClaimRefusalReason = "DifferentWork"

const LicenseOrClaimRefusalReasonDirectlicense LicenseOrClaimRefusalReason = "DirectLicense"

const LicenseOrClaimRefusalReasonDuplicatelicense LicenseOrClaimRefusalReason = "DuplicateLicense"

const LicenseOrClaimRefusalReasonDuplicaterequest LicenseOrClaimRefusalReason = "DuplicateRequest"

const LicenseOrClaimRefusalReasonImportlicenseexists LicenseOrClaimRefusalReason = "ImportLicenseExists"

const LicenseOrClaimRefusalReasonIncorrectclaim LicenseOrClaimRefusalReason = "IncorrectClaim"

const LicenseOrClaimRefusalReasonIncorrectcontrolledcompositionrate LicenseOrClaimRefusalReason = "IncorrectControlledCompositionRate"

const LicenseOrClaimRefusalReasonInhouselicenseexists LicenseOrClaimRefusalReason = "InHouseLicenseExists"

const LicenseOrClaimRefusalReasonInsufficientinformation LicenseOrClaimRefusalReason = "InsufficientInformation"

const LicenseOrClaimRefusalReasonLicenseenotauthorized LicenseOrClaimRefusalReason = "LicenseeNotAuthorized"

const LicenseOrClaimRefusalReasonMedleyrequest LicenseOrClaimRefusalReason = "MedleyRequest"

const LicenseOrClaimRefusalReasonNooptin LicenseOrClaimRefusalReason = "NoOptIn"

const LicenseOrClaimRefusalReasonNopublisherclaim LicenseOrClaimRefusalReason = "NoPublisherClaim"

const LicenseOrClaimRefusalReasonOwnershipunconfirmed LicenseOrClaimRefusalReason = "OwnershipUnconfirmed"

const LicenseOrClaimRefusalReasonProductunavailable LicenseOrClaimRefusalReason = "ProductUnavailable"

const LicenseOrClaimRefusalReasonPublishernotrepresented LicenseOrClaimRefusalReason = "PublisherNotRepresented"

const LicenseOrClaimRefusalReasonReleasewithdrawn LicenseOrClaimRefusalReason = "ReleaseWithdrawn"

const LicenseOrClaimRefusalReasonRelinquishedclaim LicenseOrClaimRefusalReason = "RelinquishedClaim"

const LicenseOrClaimRefusalReasonUserdefined LicenseOrClaimRefusalReason = "UserDefined"

const LicenseOrClaimRefusalReasonWorkdeletedfromrelease LicenseOrClaimRefusalReason = "WorkDeletedFromRelease"

const LicenseOrClaimRefusalReasonWorkincorrectlyidentified LicenseOrClaimRefusalReason = "WorkIncorrectlyIdentified"

const LicenseOrClaimRefusalReasonWorkinpublicdomain LicenseOrClaimRefusalReason = "WorkInPublicDomain"

const LicenseOrClaimRefusalReasonWorknotused LicenseOrClaimRefusalReason = "WorkNotUsed"

const LicenseOrClaimRefusalReasonWorkunknown LicenseOrClaimRefusalReason = "WorkUnknown"

type LicenseOrClaimRequestUpdateReason string

const LicenseOrClaimRequestUpdateReasonAdditionalinformationprovided LicenseOrClaimRequestUpdateReason = "AdditionalInformationProvided"

const LicenseOrClaimRequestUpdateReasonAdditionalinformationprovidedasrequested LicenseOrClaimRequestUpdateReason = "AdditionalInformationProvidedAsRequested"

const LicenseOrClaimRequestUpdateReasonUserdefined LicenseOrClaimRequestUpdateReason = "UserDefined"

type LicenseOrClaimUpdateReason string

const LicenseOrClaimUpdateReasonNewlicenseissued LicenseOrClaimUpdateReason = "NewLicenseIssued"

const LicenseOrClaimUpdateReasonNewrightshareidentified LicenseOrClaimUpdateReason = "NewRightShareIdentified"

const LicenseOrClaimUpdateReasonNewrightsholderidentified LicenseOrClaimUpdateReason = "NewRightsholderIdentified"

const LicenseOrClaimUpdateReasonNewworkidentified LicenseOrClaimUpdateReason = "NewWorkIdentified"

const LicenseOrClaimUpdateReasonRevoked LicenseOrClaimUpdateReason = "Revoked"

const LicenseOrClaimUpdateReasonUserdefined LicenseOrClaimUpdateReason = "UserDefined"

type LicenseRejectionReason string

const LicenseRejectionReasonDisagreementoverroyalties LicenseRejectionReason = "DisagreementOverRoyalties"

const LicenseRejectionReasonDisagreementoverscopeoflicense LicenseRejectionReason = "DisagreementOverScopeOfLicense"

const LicenseRejectionReasonLicenseexists LicenseRejectionReason = "LicenseExists"

const LicenseRejectionReasonLicensenotneeded LicenseRejectionReason = "LicenseNotNeeded"

const LicenseRejectionReasonWrongaddressee LicenseRejectionReason = "WrongAddressee"

const LicenseRejectionReasonUserdefined LicenseRejectionReason = "UserDefined"

const LicenseRejectionReasonWorkinpublicdomain LicenseRejectionReason = "WorkInPublicDomain"

type LicenseStatus string

const LicenseStatusActive LicenseStatus = "Active"

const LicenseStatusPending LicenseStatus = "Pending"

const LicenseStatusRevoked LicenseStatus = "Revoked"

type LicensingProcessStatus string

const LicensingProcessStatusPending LicensingProcessStatus = "Pending"

const LicensingProcessStatusProcessed LicensingProcessStatus = "Processed"

const LicensingProcessStatusThirdpartyinformationrequested LicensingProcessStatus = "ThirdPartyInformationRequested"

type MembershipType string

const MembershipTypeNationalmember MembershipType = "NationalMember"

const MembershipTypeRegionalmember MembershipType = "RegionalMember"

const MembershipTypeWorldwidemember MembershipType = "WorldwideMember"

type MessageActionType string

const MessageActionTypeBackcatalogdelivery MessageActionType = "BackCatalogDelivery"

const MessageActionTypeHighprioritydelivery MessageActionType = "HighPriorityDelivery"

const MessageActionTypeNewreleasedelivery MessageActionType = "NewReleaseDelivery"

const MessageActionTypeRedelivery MessageActionType = "ReDelivery"

const MessageActionTypeTakedown MessageActionType = "TakeDown"

const MessageActionTypeUserdefined MessageActionType = "UserDefined"

type MessageContentRevenueType string

const MessageContentRevenueTypeNontransactionalrevenue MessageContentRevenueType = "NonTransactionalRevenue"

const MessageContentRevenueTypeTransactionalrevenue MessageContentRevenueType = "TransactionalRevenue"

const MessageContentRevenueTypeUserdefined MessageContentRevenueType = "UserDefined"

type MessageControlType string

const MessageControlTypeLivemessage MessageControlType = "LiveMessage"

const MessageControlTypeTestmessage MessageControlType = "TestMessage"

type MidiType string

const MidiTypeMonophonicmidi MidiType = "MonophonicMidi"

const MidiTypePolyphonicmidi MidiType = "PolyphonicMidi"

const MidiTypeUnknown MidiType = "Unknown"

const MidiTypeUserdefined MidiType = "UserDefined"

type MlcMessageType string

const MlcMessageTypeDeclarationofsoundrecordingrightsclaimmessage MlcMessageType = "DeclarationOfSoundRecordingRightsClaimMessage"

const MlcMessageTypeRequestsoundrecordinginformationmessage MlcMessageType = "RequestSoundRecordingInformationMessage"

const MlcMessageTypeRevokesoundrecordingrightsclaimmessage MlcMessageType = "RevokeSoundRecordingRightsClaimMessage"

const MlcMessageTypeSalesreportmessage MlcMessageType = "SalesReportMessage"

const MlcMessageTypeDeclarationofrevenuemessage MlcMessageType = "DeclarationOfRevenueMessage"

type MusicalWorkContributorRole string

const MusicalWorkContributorRoleAdapter MusicalWorkContributorRole = "Adapter"

const MusicalWorkContributorRoleArranger MusicalWorkContributorRole = "Arranger"

const MusicalWorkContributorRoleAssociatedperformer MusicalWorkContributorRole = "AssociatedPerformer"

const MusicalWorkContributorRoleAuthor MusicalWorkContributorRole = "Author"

const MusicalWorkContributorRoleComposer MusicalWorkContributorRole = "Composer"

const MusicalWorkContributorRoleComposerlyricist MusicalWorkContributorRole = "ComposerLyricist"

const MusicalWorkContributorRoleContributor MusicalWorkContributorRole = "Contributor"

const MusicalWorkContributorRoleLibrettist MusicalWorkContributorRole = "Librettist"

const MusicalWorkContributorRoleLyricist MusicalWorkContributorRole = "Lyricist"

const MusicalWorkContributorRoleMusicpublisher MusicalWorkContributorRole = "MusicPublisher"

const MusicalWorkContributorRoleNonlyricauthor MusicalWorkContributorRole = "NonLyricAuthor"

const MusicalWorkContributorRoleOriginalpublisher MusicalWorkContributorRole = "OriginalPublisher"

const MusicalWorkContributorRoleSubarranger MusicalWorkContributorRole = "SubArranger"

const MusicalWorkContributorRoleSubpublisher MusicalWorkContributorRole = "SubPublisher"

const MusicalWorkContributorRoleSubstitutedpublisher MusicalWorkContributorRole = "SubstitutedPublisher"

const MusicalWorkContributorRoleTranslator MusicalWorkContributorRole = "Translator"

const MusicalWorkContributorRoleUnknown MusicalWorkContributorRole = "Unknown"

const MusicalWorkContributorRoleUserdefined MusicalWorkContributorRole = "UserDefined"

type MusicalWorkRightsClaimType string

const MusicalWorkRightsClaimTypeCopyrightcontrol MusicalWorkRightsClaimType = "CopyrightControl"

const MusicalWorkRightsClaimTypeNonmemberclaim MusicalWorkRightsClaimType = "NonMemberClaim"

const MusicalWorkRightsClaimTypePublicdomain MusicalWorkRightsClaimType = "PublicDomain"

const MusicalWorkRightsClaimTypeSocietyclaim MusicalWorkRightsClaimType = "SocietyClaim"

const MusicalWorkRightsClaimTypeUnknown MusicalWorkRightsClaimType = "Unknown"

type MusicalWorkType string

const MusicalWorkTypeAdaptedinoriginallanguage MusicalWorkType = "AdaptedInOriginalLanguage"

const MusicalWorkTypeAdaptedinstrumentalwork MusicalWorkType = "AdaptedInstrumentalWork"

const MusicalWorkTypeAdaptedwithnewlyrics MusicalWorkType = "AdaptedWithNewLyrics"

const MusicalWorkTypeArrangedwithnewmusic MusicalWorkType = "ArrangedWithNewMusic"

const MusicalWorkTypeCompositemusicalwork MusicalWorkType = "CompositeMusicalWork"

const MusicalWorkTypeDramaticomusicalwork MusicalWorkType = "DramaticoMusicalWork"

const MusicalWorkTypeLyricremoval MusicalWorkType = "LyricRemoval"

const MusicalWorkTypeLyricreplacement MusicalWorkType = "LyricReplacement"

const MusicalWorkTypeLyrictranslation MusicalWorkType = "LyricTranslation"

const MusicalWorkTypeMashup MusicalWorkType = "Mashup"

const MusicalWorkTypeMedley MusicalWorkType = "Medley"

const MusicalWorkTypeMultimediaproductionwork MusicalWorkType = "MultimediaProductionWork"

const MusicalWorkTypeMusicalworkmovement MusicalWorkType = "MusicalWorkMovement"

const MusicalWorkTypeMusicalworkwithsamples MusicalWorkType = "MusicalWorkWithSamples"

const MusicalWorkTypeMusicarrangement MusicalWorkType = "MusicArrangement"

const MusicalWorkTypeMusicarrangementoftext MusicalWorkType = "MusicArrangementOfText"

const MusicalWorkTypeOriginallyricsarrangement MusicalWorkType = "OriginalLyricsArrangement"

const MusicalWorkTypeOriginalmusicadaptation MusicalWorkType = "OriginalMusicAdaptation"

const MusicalWorkTypeOriginalmusicalwork MusicalWorkType = "OriginalMusicalWork"

const MusicalWorkTypePotpourri MusicalWorkType = "Potpourri"

const MusicalWorkTypeProductionmusiclibrarywork MusicalWorkType = "ProductionMusicLibraryWork"

const MusicalWorkTypeRadioproductionwork MusicalWorkType = "RadioProductionWork"

const MusicalWorkTypeTheaterproductionwork MusicalWorkType = "TheaterProductionWork"

const MusicalWorkTypeTvproductionwork MusicalWorkType = "TvProductionWork"

const MusicalWorkTypeUnknown MusicalWorkType = "Unknown"

const MusicalWorkTypeUnspecifiedarrangement MusicalWorkType = "UnspecifiedArrangement"

const MusicalWorkTypeUnspecifiedmusicalworkexcerpt MusicalWorkType = "UnspecifiedMusicalWorkExcerpt"

const MusicalWorkTypeUserdefined MusicalWorkType = "UserDefined"

const MusicalWorkTypeVideoproductionwork MusicalWorkType = "VideoProductionWork"

type MwlCaCMessageInBatchType string

const MwlCaCMessageInBatchTypeLicenseorclaimrequestmessage MwlCaCMessageInBatchType = "LicenseOrClaimRequestMessage"

const MwlCaCMessageInBatchTypeLicenseorclaimmessage MwlCaCMessageInBatchType = "LicenseOrClaimMessage"

const MwlCaCMessageInBatchTypeLicensinginformationrequestmessage MwlCaCMessageInBatchType = "LicensingInformationRequestMessage"

const MwlCaCMessageInBatchTypeLicenseorclaimconfirmationmessage MwlCaCMessageInBatchType = "LicenseOrClaimConfirmationMessage"

const MwlCaCMessageInBatchTypeNewreleasemessage MwlCaCMessageInBatchType = "NewReleaseMessage"

const MwlCaCMessageInBatchTypeContractdeliverymessage MwlCaCMessageInBatchType = "ContractDeliveryMessage"

const MwlCaCMessageInBatchTypeProductdeletionmessage MwlCaCMessageInBatchType = "ProductDeletionMessage"

type NewReleaseMessageStatus string

const NewReleaseMessageStatusNewreleasemessagenotprovided NewReleaseMessageStatus = "NewReleaseMessageNotProvided"

const NewReleaseMessageStatusNewreleasemessageprovided NewReleaseMessageStatus = "NewReleaseMessageProvided"

type NonIsoTerritoryCode string

const NonIsoTerritoryCodeWorldwide NonIsoTerritoryCode = "Worldwide"

type OperatingSystemType string

const OperatingSystemTypeMacos OperatingSystemType = "MacOS"

const OperatingSystemTypeMswindows OperatingSystemType = "MsWindows"

const OperatingSystemTypeSymbian OperatingSystemType = "Symbian"

const OperatingSystemTypeUnknown OperatingSystemType = "Unknown"

type OrderType string

const OrderTypeBackcatalogorder OrderType = "BackCatalogOrder"

const OrderTypeExpressorder OrderType = "ExpressOrder"

const OrderTypeHarddiskorder OrderType = "HardDiskOrder"

const OrderTypeMetadataonlyorder OrderType = "MetadataOnlyOrder"

const OrderTypeNewreleaseorder OrderType = "NewReleaseOrder"

const OrderTypeOffcyclerushorder OrderType = "OffCycleRushOrder"

const OrderTypePreorder OrderType = "PreOrder"

const OrderTypeRedeliveryorder OrderType = "ReDeliveryOrder"

const OrderTypeTakedownorder OrderType = "TakeDownOrder"

const OrderTypeUserdefined OrderType = "UserDefined"

type PLineType string

const PLineTypeOriginalpline PLineType = "OriginalPLine"

const PLineTypeRemasteringpline PLineType = "RemasteringPLine"

type ParentalWarningType string

const ParentalWarningTypeExplicit ParentalWarningType = "Explicit"

const ParentalWarningTypeExplicitcontentedited ParentalWarningType = "ExplicitContentEdited"

const ParentalWarningTypeNoadviceavailable ParentalWarningType = "NoAdviceAvailable"

const ParentalWarningTypeNotexplicit ParentalWarningType = "NotExplicit"

const ParentalWarningTypeUnknown ParentalWarningType = "Unknown"

const ParentalWarningTypeUserdefined ParentalWarningType = "UserDefined"

type PercentageType string

const PercentageTypePercentageoffreegoodspermitted PercentageType = "PercentageOfFreeGoodsPermitted"

const PercentageTypePercentageofgrossrevenue PercentageType = "PercentageOfGrossRevenue"

const PercentageTypePercentageofnetrevenue PercentageType = "PercentageOfNetRevenue"

const PercentageTypePercentageofnetsales PercentageType = "PercentageOfNetSales"

const PercentageTypePercentageofpriceconsumerpaid PercentageType = "PercentageOfPriceConsumerPaid"

const PercentageTypePercentageofstatutoryroyaltyrate PercentageType = "PercentageOfStatutoryRoyaltyRate"

type PriceRangeType string

type PriceType string

type Priority string

const PriorityHigh Priority = "High"

const PriorityLow Priority = "Low"

const PriorityNormal Priority = "Normal"

type ProductType string

const ProductTypeAudioproduct ProductType = "AudioProduct"

const ProductTypeGraphicsproduct ProductType = "GraphicsProduct"

const ProductTypeMixedmediabundleproduct ProductType = "MixedMediaBundleProduct"

const ProductTypeMobileproduct ProductType = "MobileProduct"

const ProductTypeUserdefined ProductType = "UserDefined"

const ProductTypeVideoproduct ProductType = "VideoProduct"

type Purpose string

const PurposeBackgroundmusic Purpose = "BackgroundMusic"

const PurposeChanneltrailermusic Purpose = "ChannelTrailerMusic"

const PurposeExtract Purpose = "Extract"

const PurposeFilmtrailermusic Purpose = "FilmTrailerMusic"

const PurposeForegroundmusic Purpose = "ForegroundMusic"

const PurposeTrailermusic Purpose = "TrailerMusic"

const PurposeUserdefined Purpose = "UserDefined"

type RateModificationType string

const RateModificationTypeMultiplediscprovision RateModificationType = "MultipleDiscProvision"

const RateModificationTypeOtherprovision RateModificationType = "OtherProvision"

const RateModificationTypeSalesvolumeprovision RateModificationType = "SalesVolumeProvision"

const RateModificationTypeVideoprovision RateModificationType = "VideoProvision"

type RatingAgency string

const RatingAgencyAfr RatingAgency = "AFR"

const RatingAgencyBbfc RatingAgency = "BBFC"

const RatingAgencyBfco RatingAgency = "BFCO"

const RatingAgencyBfsc RatingAgency = "BFSC"

const RatingAgencyBmukk RatingAgency = "BMUKK"

const RatingAgencyCbfc RatingAgency = "CBFC"

const RatingAgencyCcc RatingAgency = "CCC"

const RatingAgencyCce RatingAgency = "CCE"

const RatingAgencyChvrs RatingAgency = "CHVRS"

const RatingAgencyCnc RatingAgency = "CNC"

const RatingAgencyDjctq RatingAgency = "DJCTQ"

const RatingAgencyEirin RatingAgency = "Eirin"

const RatingAgencyFcb RatingAgency = "FCB"

const RatingAgencyFilmtilsynet RatingAgency = "Filmtilsynet"

const RatingAgencyFpb RatingAgency = "FPB"

const RatingAgencyFsk RatingAgency = "FSK"

const RatingAgencyIfco RatingAgency = "IFCO"

const RatingAgencyIncaa RatingAgency = "INCAA"

const RatingAgencyKmrb RatingAgency = "KMRB"

const RatingAgencyKr RatingAgency = "KR"

const RatingAgencyKrrit RatingAgency = "KRRIT"

const RatingAgencyLsf RatingAgency = "LSF"

const RatingAgencyMbu RatingAgency = "MBU"

const RatingAgencyMda RatingAgency = "MDA"

const RatingAgencyMdcb RatingAgency = "MDCB"

const RatingAgencyMfcb RatingAgency = "MFCB"

const RatingAgencyMic RatingAgency = "MIC"

const RatingAgencyMpaa RatingAgency = "MPAA"

const RatingAgencyMtrcb RatingAgency = "MTRCB"

const RatingAgencyNbc RatingAgency = "NBC"

const RatingAgencyNfvcb RatingAgency = "NFVCB"

const RatingAgencyNicam RatingAgency = "NICAM"

const RatingAgencyNkc RatingAgency = "NKC"

const RatingAgencyOflc RatingAgency = "OFLC"

const RatingAgencyOflcNz RatingAgency = "OFLC-NZ"

const RatingAgencyOfrb RatingAgency = "OFRB"

const RatingAgencyRdcq RatingAgency = "RDCQ"

const RatingAgencyRtc RatingAgency = "RTC"

const RatingAgencySbb RatingAgency = "SBB"

const RatingAgencySmais RatingAgency = "Smais"

const RatingAgencySpioJk RatingAgency = "SPIO-JK"

const RatingAgencyTela RatingAgency = "TELA"

const RatingAgencyUserdefined RatingAgency = "UserDefined"

const RatingAgencyVet RatingAgency = "VET"

type ReasonType string

const ReasonTypeChartreporting ReasonType = "ChartReporting"

const ReasonTypeRoyaltyreporting ReasonType = "RoyaltyReporting"

const ReasonTypeUserdefined ReasonType = "UserDefined"

type RecipientRevenueType string

const RecipientRevenueTypePerformerandproducerrevenue RecipientRevenueType = "PerformerAndProducerRevenue"

const RecipientRevenueTypePerformerrevenue RecipientRevenueType = "PerformerRevenue"

const RecipientRevenueTypeProducerrevenue RecipientRevenueType = "ProducerRevenue"

type RecordingMode string

const RecordingModeMono RecordingMode = "Mono"

const RecordingModeMultichannelaudio RecordingMode = "MultichannelAudio"

const RecordingModeStereo RecordingMode = "Stereo"

const RecordingModeUnknown RecordingMode = "Unknown"

type RedeliveryReasonType string

const RedeliveryReasonTypeBinarycorrupted RedeliveryReasonType = "BinaryCorrupted"

const RedeliveryReasonTypeMetadatainadequate RedeliveryReasonType = "MetadataInadequate"

const RedeliveryReasonTypePackageincomplete RedeliveryReasonType = "PackageIncomplete"

const RedeliveryReasonTypeProcessingerroratreleasedistributor RedeliveryReasonType = "ProcessingErrorAtReleaseDistributor"

const RedeliveryReasonTypeUserdefined RedeliveryReasonType = "UserDefined"

type ReferenceUnit string

const ReferenceUnitPerlicense ReferenceUnit = "PerLicense"

const ReferenceUnitPeruse ReferenceUnit = "PerUse"

type RelationalRelator string

const RelationalRelatorEqualto RelationalRelator = "EqualTo"

const RelationalRelatorLessthan RelationalRelator = "LessThan"

const RelationalRelatorLessthanorequalto RelationalRelator = "LessThanOrEqualTo"

const RelationalRelatorMorethan RelationalRelator = "MoreThan"

const RelationalRelatorMorethanorequalto RelationalRelator = "MoreThanOrEqualTo"

const RelationalRelatorNotequalto RelationalRelator = "NotEqualTo"

type ReleaseAvailabilityStatus string

const ReleaseAvailabilityStatusAvailablefordsp ReleaseAvailabilityStatus = "AvailableForDSP"

const ReleaseAvailabilityStatusNotavailablefordsp ReleaseAvailabilityStatus = "NotAvailableForDSP"

const ReleaseAvailabilityStatusNotclearedfordsp ReleaseAvailabilityStatus = "NotClearedForDSP"

const ReleaseAvailabilityStatusNotclearedforterritory ReleaseAvailabilityStatus = "NotClearedForTerritory"

const ReleaseAvailabilityStatusNotyetprepared ReleaseAvailabilityStatus = "NotYetPrepared"

const ReleaseAvailabilityStatusUserdefined ReleaseAvailabilityStatus = "UserDefined"

type ReleaseRelationshipType string

const ReleaseRelationshipTypeHasartistfromensemble ReleaseRelationshipType = "HasArtistFromEnsemble"

const ReleaseRelationshipTypeHasartistfromsameensemble ReleaseRelationshipType = "HasArtistFromSameEnsemble"

const ReleaseRelationshipTypeHasensemblewithartist ReleaseRelationshipType = "HasEnsembleWithArtist"

const ReleaseRelationshipTypeHassameartist ReleaseRelationshipType = "HasSameArtist"

const ReleaseRelationshipTypeHassamerecordingproject ReleaseRelationshipType = "HasSameRecordingProject"

const ReleaseRelationshipTypeHassimilarcontent ReleaseRelationshipType = "HasSimilarContent"

const ReleaseRelationshipTypeIsdigitalequivalenttophysical ReleaseRelationshipType = "IsDigitalEquivalentToPhysical"

const ReleaseRelationshipTypeIsequivalenttoaudio ReleaseRelationshipType = "IsEquivalentToAudio"

const ReleaseRelationshipTypeIsequivalenttovideo ReleaseRelationshipType = "IsEquivalentToVideo"

const ReleaseRelationshipTypeIsextendedfromalbum ReleaseRelationshipType = "IsExtendedFromAlbum"

const ReleaseRelationshipTypeIsfromaudio ReleaseRelationshipType = "IsFromAudio"

const ReleaseRelationshipTypeIsfromvideo ReleaseRelationshipType = "IsFromVideo"

const ReleaseRelationshipTypeIsparentrelease ReleaseRelationshipType = "IsParentRelease"

const ReleaseRelationshipTypeIsphysicalequivalenttodigital ReleaseRelationshipType = "IsPhysicalEquivalentToDigital"

const ReleaseRelationshipTypeIsreleasefromrelease ReleaseRelationshipType = "IsReleaseFromRelease"

const ReleaseRelationshipTypeIsshortenedfromalbum ReleaseRelationshipType = "IsShortenedFromAlbum"

const ReleaseRelationshipTypeUnknown ReleaseRelationshipType = "Unknown"

const ReleaseRelationshipTypeUserdefined ReleaseRelationshipType = "UserDefined"

type ReleaseResourceType string

const ReleaseResourceTypePrimaryresource ReleaseResourceType = "PrimaryResource"

const ReleaseResourceTypeSecondaryresource ReleaseResourceType = "SecondaryResource"

type ReleaseType string

const ReleaseTypeAdvertisementvideo ReleaseType = "AdvertisementVideo"

const ReleaseTypeAlbum ReleaseType = "Album"

const ReleaseTypeAlerttonerelease ReleaseType = "AlertToneRelease"

const ReleaseTypeAnimation ReleaseType = "Animation"

const ReleaseTypeAspercontract ReleaseType = "AsPerContract"

const ReleaseTypeAudiobookrelease ReleaseType = "AudioBookRelease"

const ReleaseTypeAudiocliprelease ReleaseType = "AudioClipRelease"

const ReleaseTypeBackcoverimagerelease ReleaseType = "BackCoverImageRelease"

const ReleaseTypeBookletbackimagerelease ReleaseType = "BookletBackImageRelease"

const ReleaseTypeBookletfrontimagerelease ReleaseType = "BookletFrontImageRelease"

const ReleaseTypeBookletrelease ReleaseType = "BookletRelease"

const ReleaseTypeBundle ReleaseType = "Bundle"

const ReleaseTypeClassicalalbum ReleaseType = "ClassicalAlbum"

const ReleaseTypeConcertvideo ReleaseType = "ConcertVideo"

const ReleaseTypeCorporatefilm ReleaseType = "CorporateFilm"

const ReleaseTypeDigitalboxsetrelease ReleaseType = "DigitalBoxSetRelease"

const ReleaseTypeDocumentary ReleaseType = "Documentary"

const ReleaseTypeDocumentimagerelease ReleaseType = "DocumentImageRelease"

const ReleaseTypeEbookrelease ReleaseType = "EBookRelease"

const ReleaseTypeEpisode ReleaseType = "Episode"

const ReleaseTypeFeaturefilm ReleaseType = "FeatureFilm"

const ReleaseTypeFrontcoverimagerelease ReleaseType = "FrontCoverImageRelease"

const ReleaseTypeIconrelease ReleaseType = "IconRelease"

const ReleaseTypeInfomercialvideo ReleaseType = "InfomercialVideo"

const ReleaseTypeInteractivebookletrelease ReleaseType = "InteractiveBookletRelease"

const ReleaseTypeKaraokerelease ReleaseType = "KaraokeRelease"

const ReleaseTypeLiveeventvideo ReleaseType = "LiveEventVideo"

const ReleaseTypeLogorelease ReleaseType = "LogoRelease"

const ReleaseTypeLongformmusicalworkvideorelease ReleaseType = "LongFormMusicalWorkVideoRelease"

const ReleaseTypeLongformnonmusicalworkvideorelease ReleaseType = "LongFormNonMusicalWorkVideoRelease"

const ReleaseTypeLyricsheetrelease ReleaseType = "LyricSheetRelease"

const ReleaseTypeMusicalworkbasedgamerelease ReleaseType = "MusicalWorkBasedGameRelease"

const ReleaseTypeMusicalworkcliprelease ReleaseType = "MusicalWorkClipRelease"

const ReleaseTypeMusicalworkreadalongvideorelease ReleaseType = "MusicalWorkReadalongVideoRelease"

const ReleaseTypeMusicalworktrailerrelease ReleaseType = "MusicalWorkTrailerRelease"

const ReleaseTypeMusicalworkvideochapterrelease ReleaseType = "MusicalWorkVideoChapterRelease"

const ReleaseTypeNews ReleaseType = "News"

const ReleaseTypeNonmusicalworkbasedgamerelease ReleaseType = "NonMusicalWorkBasedGameRelease"

const ReleaseTypeNonmusicalworkcliprelease ReleaseType = "NonMusicalWorkClipRelease"

const ReleaseTypeNonmusicalworkreadalongvideorelease ReleaseType = "NonMusicalWorkReadalongVideoRelease"

const ReleaseTypeNonmusicalworktrailerrelease ReleaseType = "NonMusicalWorkTrailerRelease"

const ReleaseTypeNonmusicalworkvideochapterrelease ReleaseType = "NonMusicalWorkVideoChapterRelease"

const ReleaseTypeNonserialaudiovisualrecording ReleaseType = "NonSerialAudioVisualRecording"

const ReleaseTypePhotographrelease ReleaseType = "PhotographRelease"

const ReleaseTypeRingbacktonerelease ReleaseType = "RingbackToneRelease"

const ReleaseTypeRingtonerelease ReleaseType = "RingtoneRelease"

const ReleaseTypeScreensaverrelease ReleaseType = "ScreensaverRelease"

const ReleaseTypeSeason ReleaseType = "Season"

const ReleaseTypeSeries ReleaseType = "Series"

const ReleaseTypeSheetmusicrelease ReleaseType = "SheetMusicRelease"

const ReleaseTypeShortformmusicalworkvideorelease ReleaseType = "ShortFormMusicalWorkVideoRelease"

const ReleaseTypeShortformnonmusicalworkvideorelease ReleaseType = "ShortFormNonMusicalWorkVideoRelease"

const ReleaseTypeSingle ReleaseType = "Single"

const ReleaseTypeSingleresourcerelease ReleaseType = "SingleResourceRelease"

const ReleaseTypeTrackrelease ReleaseType = "TrackRelease"

const ReleaseTypeTrailervideo ReleaseType = "TrailerVideo"

const ReleaseTypeTrayimagerelease ReleaseType = "TrayImageRelease"

const ReleaseTypeUnknown ReleaseType = "Unknown"

const ReleaseTypeUserdefined ReleaseType = "UserDefined"

const ReleaseTypeVideoalbum ReleaseType = "VideoAlbum"

const ReleaseTypeVideochapterrelease ReleaseType = "VideoChapterRelease"

const ReleaseTypeVideocliprelease ReleaseType = "VideoClipRelease"

const ReleaseTypeVideoscreencapturerelease ReleaseType = "VideoScreenCaptureRelease"

const ReleaseTypeVideosingle ReleaseType = "VideoSingle"

const ReleaseTypeVideotrackrelease ReleaseType = "VideoTrackRelease"

const ReleaseTypeWallpaperrelease ReleaseType = "WallpaperRelease"

type ReportFormat string

const ReportFormatAscii ReportFormat = "ASCII"

const ReportFormatCsv ReportFormat = "CSV"

const ReportFormatExcel2000 ReportFormat = "Excel2000"

const ReportFormatExcel2007 ReportFormat = "Excel2007"

const ReportFormatExcel2010 ReportFormat = "Excel2010"

const ReportFormatUserdefined ReportFormat = "UserDefined"

const ReportFormatXml ReportFormat = "XML"

type ReportType string

const ReportTypeDeliveryfrequencyrequestcall ReportType = "DeliveryFrequencyRequestCall"

const ReportTypeInformationaboutdeliveredandavailablereleasescall ReportType = "InformationAboutDeliveredAndAvailableReleasesCall"

const ReportTypeOrderedreleasesinqueuerequestcall ReportType = "OrderedReleasesInQueueRequestCall"

const ReportTypeRedeliveryrequestcall ReportType = "RedeliveryRequestCall"

const ReportTypeReleaseavailabilitycall ReportType = "ReleaseAvailabilityCall"

const ReportTypeReleaseavailabilityrequestcall ReportType = "ReleaseAvailabilityRequestCall"

const ReportTypeReleasestatusinformationcall ReportType = "ReleaseStatusInformationCall"

const ReportTypeReleasestatusrequestcall ReportType = "ReleaseStatusRequestCall"

const ReportTypeReleasesupplychainrequestcall ReportType = "ReleaseSupplyChainRequestCall"

const ReportTypeReportdeliverycall ReportType = "ReportDeliveryCall"

const ReportTypeReportrequestcall ReportType = "ReportRequestCall"

const ReportTypeSupplychainstatuscall ReportType = "SupplyChainStatusCall"

const ReportTypeUserdefined ReportType = "UserDefined"

type RequestedActionType string

const RequestedActionTypeAdditionalinformationonly RequestedActionType = "AdditionalInformationOnly"

const RequestedActionTypeCorrectandinform RequestedActionType = "CorrectAndInform"

const RequestedActionTypeCorrectandresend RequestedActionType = "CorrectAndResend"

const RequestedActionTypeNoaction RequestedActionType = "NoAction"

const RequestedActionTypeUserdefined RequestedActionType = "UserDefined"

type ResourceContributorRole string

const ResourceContributorRoleActor ResourceContributorRole = "Actor"

const ResourceContributorRoleArchitect ResourceContributorRole = "Architect"

const ResourceContributorRoleArtist ResourceContributorRole = "Artist"

const ResourceContributorRoleAssociatedperformer ResourceContributorRole = "AssociatedPerformer"

const ResourceContributorRoleBand ResourceContributorRole = "Band"

const ResourceContributorRoleBookpublisher ResourceContributorRole = "BookPublisher"

const ResourceContributorRoleCartoonist ResourceContributorRole = "Cartoonist"

const ResourceContributorRoleChoir ResourceContributorRole = "Choir"

const ResourceContributorRoleChoreographer ResourceContributorRole = "Choreographer"

const ResourceContributorRoleComputergraphiccreator ResourceContributorRole = "ComputerGraphicCreator"

const ResourceContributorRoleConductor ResourceContributorRole = "Conductor"

const ResourceContributorRoleContributor ResourceContributorRole = "Contributor"

const ResourceContributorRoleCostumedesigner ResourceContributorRole = "CostumeDesigner"

const ResourceContributorRoleDesigner ResourceContributorRole = "Designer"

const ResourceContributorRoleEnsemble ResourceContributorRole = "Ensemble"

const ResourceContributorRoleFeaturedartist ResourceContributorRole = "FeaturedArtist"

const ResourceContributorRoleFilmdirector ResourceContributorRole = "FilmDirector"

const ResourceContributorRoleFilmdistributor ResourceContributorRole = "FilmDistributor"

const ResourceContributorRoleFilmeditor ResourceContributorRole = "FilmEditor"

const ResourceContributorRoleFilmproducer ResourceContributorRole = "FilmProducer"

const ResourceContributorRoleFilmsoundengineer ResourceContributorRole = "FilmSoundEngineer"

const ResourceContributorRoleGraphicartist ResourceContributorRole = "GraphicArtist"

const ResourceContributorRoleGraphicdesigner ResourceContributorRole = "GraphicDesigner"

const ResourceContributorRoleJournalist ResourceContributorRole = "Journalist"

const ResourceContributorRoleMainartist ResourceContributorRole = "MainArtist"

const ResourceContributorRoleNewspaperpublisher ResourceContributorRole = "NewspaperPublisher"

const ResourceContributorRoleOrchestra ResourceContributorRole = "Orchestra"

const ResourceContributorRolePainter ResourceContributorRole = "Painter"

const ResourceContributorRolePeriodicalpublisher ResourceContributorRole = "PeriodicalPublisher"

const ResourceContributorRolePhotographer ResourceContributorRole = "Photographer"

const ResourceContributorRolePhotographydirector ResourceContributorRole = "PhotographyDirector"

const ResourceContributorRolePrimarymusician ResourceContributorRole = "PrimaryMusician"

const ResourceContributorRoleProducer ResourceContributorRole = "Producer"

const ResourceContributorRoleProgrammer ResourceContributorRole = "Programmer"

const ResourceContributorRoleRightscontrolleronproduct ResourceContributorRole = "RightsControllerOnProduct"

const ResourceContributorRoleScreenplayauthor ResourceContributorRole = "ScreenplayAuthor"

const ResourceContributorRoleSetdesigner ResourceContributorRole = "SetDesigner"

const ResourceContributorRoleSoloist ResourceContributorRole = "Soloist"

const ResourceContributorRoleStagedirector ResourceContributorRole = "StageDirector"

const ResourceContributorRoleStudiopersonnel ResourceContributorRole = "StudioPersonnel"

const ResourceContributorRoleSubtitleseditor ResourceContributorRole = "SubtitlesEditor"

const ResourceContributorRoleSubtitlestranslator ResourceContributorRole = "SubtitlesTranslator"

const ResourceContributorRoleUnknown ResourceContributorRole = "Unknown"

const ResourceContributorRoleUserdefined ResourceContributorRole = "UserDefined"

type ResourceOmissionReason string

const ResourceOmissionReasonPassportservicerelease ResourceOmissionReason = "PassportServiceRelease"

const ResourceOmissionReasonPrerelease ResourceOmissionReason = "PreRelease"

const ResourceOmissionReasonUserdefined ResourceOmissionReason = "UserDefined"

const ResourceOmissionReasonVirtualrelease ResourceOmissionReason = "VirtualRelease"

type ResourceType string

const ResourceTypeImage ResourceType = "Image"

const ResourceTypeMidi ResourceType = "MIDI"

const ResourceTypeSheetmusic ResourceType = "SheetMusic"

const ResourceTypeSoftware ResourceType = "Software"

const ResourceTypeSoundrecording ResourceType = "SoundRecording"

const ResourceTypeText ResourceType = "Text"

const ResourceTypeUserdefinedresource ResourceType = "UserDefinedResource"

const ResourceTypeVideo ResourceType = "Video"

type RevenueSourceType string

const RevenueSourceTypeFinancialrevenue RevenueSourceType = "FinancialRevenue"

const RevenueSourceTypeIndemnityrevenue RevenueSourceType = "IndemnityRevenue"

const RevenueSourceTypeRoyaltyrevenue RevenueSourceType = "RoyaltyRevenue"

type RightsClaimPolicyType string

const RightsClaimPolicyTypeReportusage RightsClaimPolicyType = "ReportUsage"

const RightsClaimPolicyTypeBlockaccess RightsClaimPolicyType = "BlockAccess"

const RightsClaimPolicyTypeMonetize RightsClaimPolicyType = "Monetize"

type RightsControllerRole string

const RightsControllerRoleAdministratingrecordcompany RightsControllerRole = "AdministratingRecordCompany"

const RightsControllerRoleRightsadministrator RightsControllerRole = "RightsAdministrator"

const RightsControllerRoleRightscontroller RightsControllerRole = "RightsController"

const RightsControllerRoleRoyaltyadministrator RightsControllerRole = "RoyaltyAdministrator"

const RightsControllerRoleUnknown RightsControllerRole = "Unknown"

type RightsControllerType string

const RightsControllerTypeOriginalowner RightsControllerType = "OriginalOwner"

const RightsControllerTypeSuccessorintitle RightsControllerType = "SuccessorInTitle"

const RightsControllerTypeExclusivelicensee RightsControllerType = "ExclusiveLicensee"

type RightsCoverage string

const RightsCoverageMakeavailableright RightsCoverage = "MakeAvailableRight"

const RightsCoverageMechanicalright RightsCoverage = "MechanicalRight"

const RightsCoveragePerformingright RightsCoverage = "PerformingRight"

const RightsCoverageReproductionright RightsCoverage = "ReproductionRight"

const RightsCoverageSynchronizationright RightsCoverage = "SynchronizationRight"

type RoyaltyRateCalculationType string

const RoyaltyRateCalculationTypeBudgetroyaltyrate RoyaltyRateCalculationType = "BudgetRoyaltyRate"

const RoyaltyRateCalculationTypeControlledcompositionroyaltyrate RoyaltyRateCalculationType = "ControlledCompositionRoyaltyRate"

const RoyaltyRateCalculationTypeControlledshareroyaltyrate RoyaltyRateCalculationType = "ControlledShareRoyaltyRate"

const RoyaltyRateCalculationTypeMinimumstatutoryroyaltyrate RoyaltyRateCalculationType = "MinimumStatutoryRoyaltyRate"

const RoyaltyRateCalculationTypeNegotiatedroyaltyrate RoyaltyRateCalculationType = "NegotiatedRoyaltyRate"

const RoyaltyRateCalculationTypeReducedroyaltyrate RoyaltyRateCalculationType = "ReducedRoyaltyRate"

const RoyaltyRateCalculationTypeReducedstatutoryroyaltyrate RoyaltyRateCalculationType = "ReducedStatutoryRoyaltyRate"

const RoyaltyRateCalculationTypeStatutoryroyaltyrate RoyaltyRateCalculationType = "StatutoryRoyaltyRate"

type RoyaltyRateType string

const RoyaltyRateTypePennyrate RoyaltyRateType = "PennyRate"

const RoyaltyRateTypePercentageroyaltyrate RoyaltyRateType = "PercentageRoyaltyRate"

const RoyaltyRateTypeUserdefined RoyaltyRateType = "UserDefined"

type SalesReportAvailabilityStatus string

const SalesReportAvailabilityStatusSalesreportavailable SalesReportAvailabilityStatus = "SalesReportAvailable"

const SalesReportAvailabilityStatusSalesreportnotavailable SalesReportAvailabilityStatus = "SalesReportNotAvailable"

type Sex string

const SexFemale Sex = "Female"

const SexMale Sex = "Male"

const SexUnknown Sex = "Unknown"

type SheetMusicCodecType string

type SheetMusicType string

type SoftwareType string

const SoftwareTypeInteractivebooklet SoftwareType = "InteractiveBooklet"

const SoftwareTypeMusicalworkbasedgame SoftwareType = "MusicalWorkBasedGame"

const SoftwareTypeNonmusicalworkbasedgame SoftwareType = "NonMusicalWorkBasedGame"

const SoftwareTypeScreensaver SoftwareType = "Screensaver"

const SoftwareTypeUnknown SoftwareType = "Unknown"

const SoftwareTypeUserdefined SoftwareType = "UserDefined"

type SoundProcessorType string

const SoundProcessorTypeMidiprocessor SoundProcessorType = "MidiProcessor"

const SoundProcessorTypeSmafMa2 SoundProcessorType = "SMAF-MA2"

const SoundProcessorTypeSmafMa3 SoundProcessorType = "SMAF-MA3"

const SoundProcessorTypeUnknown SoundProcessorType = "Unknown"

const SoundProcessorTypeUserdefined SoundProcessorType = "UserDefined"

type SoundRecordingType string

const SoundRecordingTypeMusicalworkreadalongsoundrecording SoundRecordingType = "MusicalWorkReadalongSoundRecording"

const SoundRecordingTypeMusicalworksoundrecording SoundRecordingType = "MusicalWorkSoundRecording"

const SoundRecordingTypeNonmusicalworkreadalongsoundrecording SoundRecordingType = "NonMusicalWorkReadalongSoundRecording"

const SoundRecordingTypeNonmusicalworksoundrecording SoundRecordingType = "NonMusicalWorkSoundRecording"

const SoundRecordingTypeUnknown SoundRecordingType = "Unknown"

const SoundRecordingTypeUserdefined SoundRecordingType = "UserDefined"

type SupplyChainStatus string

const SupplyChainStatusDeliveredtoreleasedistributor SupplyChainStatus = "DeliveredToReleaseDistributor"

const SupplyChainStatusIndeliverytoreleasedistributor SupplyChainStatus = "InDeliveryToReleaseDistributor"

const SupplyChainStatusInpreparationfordeliverytoreleasedistributor SupplyChainStatus = "InPreparationForDeliveryToReleaseDistributor"

const SupplyChainStatusOrderplacedforreleasedistributor SupplyChainStatus = "OrderPlacedForReleaseDistributor"

const SupplyChainStatusProcessingerroratreleasecreator SupplyChainStatus = "ProcessingErrorAtReleaseCreator"

const SupplyChainStatusProcessingerroratreleasedistributor SupplyChainStatus = "ProcessingErrorAtReleaseDistributor"

const SupplyChainStatusReleasemadeavailabletoconsumers SupplyChainStatus = "ReleaseMadeAvailableToConsumers"

const SupplyChainStatusReleasenotavailable SupplyChainStatus = "ReleaseNotAvailable"

const SupplyChainStatusReleasereceivedbyreleasedistributor SupplyChainStatus = "ReleaseReceivedByReleaseDistributor"

const SupplyChainStatusReleasestagedforpublication SupplyChainStatus = "ReleaseStagedForPublication"

const SupplyChainStatusSuccessfullyingestedbyreleasedistributor SupplyChainStatus = "SuccessfullyIngestedByReleaseDistributor"

const SupplyChainStatusUserdefined SupplyChainStatus = "UserDefined"

type TaxScope string

const TaxScopeCombinedtax TaxScope = "CombinedTax"

const TaxScopeFederaltax TaxScope = "FederalTax"

const TaxScopeLocaltax TaxScope = "LocalTax"

const TaxScopeProvincialtax TaxScope = "ProvincialTax"

const TaxScopeStatetax TaxScope = "StateTax"

const TaxScopeUserdefined TaxScope = "UserDefined"

type TaxType string

const TaxTypeCombinedtax TaxType = "CombinedTax"

const TaxTypeSalestax TaxType = "SalesTax"

const TaxTypeServicetax TaxType = "ServiceTax"

const TaxTypeSourcetax TaxType = "SourceTax"

const TaxTypeUserdefined TaxType = "UserDefined"

type TextCodecType string

const TextCodecTypeAscii TextCodecType = "ASCII"

const TextCodecTypeHtml TextCodecType = "HTML"

const TextCodecTypePdf TextCodecType = "PDF"

const TextCodecTypePostscript TextCodecType = "PostScript"

const TextCodecTypeRtf TextCodecType = "RTF"

const TextCodecTypeUnknown TextCodecType = "Unknown"

const TextCodecTypeUserdefined TextCodecType = "UserDefined"

type TextType string

const TextTypeEbook TextType = "EBook"

const TextTypeLinernotes TextType = "LinerNotes"

const TextTypeLyrictext TextType = "LyricText"

const TextTypeNoninteractivebooklet TextType = "NonInteractiveBooklet"

const TextTypeTextdocument TextType = "TextDocument"

const TextTypeUnknown TextType = "Unknown"

const TextTypeUserdefined TextType = "UserDefined"

type ThemeType string

const ThemeTypeClosingtheme ThemeType = "ClosingTheme"

const ThemeTypeMaintheme ThemeType = "MainTheme"

const ThemeTypeOpeningtheme ThemeType = "OpeningTheme"

const ThemeTypeSegmenttheme ThemeType = "SegmentTheme"

const ThemeTypeTitletheme ThemeType = "TitleTheme"

const ThemeTypeUserdefined ThemeType = "UserDefined"

type TitleType string

const TitleTypeAbbreviateddisplaytitle TitleType = "AbbreviatedDisplayTitle"

const TitleTypeAlternativetitle TitleType = "AlternativeTitle"

const TitleTypeDisplaytitle TitleType = "DisplayTitle"

const TitleTypeFirstlineoftext TitleType = "FirstLineOfText"

const TitleTypeFormaltitle TitleType = "FormalTitle"

const TitleTypeGroupingtitle TitleType = "GroupingTitle"

const TitleTypeIncorrecttitle TitleType = "IncorrectTitle"

const TitleTypeMisspelledtitle TitleType = "MisspelledTitle"

const TitleTypeOriginaltitle TitleType = "OriginalTitle"

const TitleTypeSearchtitle TitleType = "SearchTitle"

const TitleTypeSortingtitle TitleType = "SortingTitle"

const TitleTypeTitleaspart TitleType = "TitleAsPart"

const TitleTypeTitlewithoutpunctuation TitleType = "TitleWithoutPunctuation"

const TitleTypeTranslatedtitle TitleType = "TranslatedTitle"

const TitleTypeUnknown TitleType = "Unknown"

const TitleTypeUserdefined TitleType = "UserDefined"

type UnitOfBitRate string

const UnitOfBitRateBps UnitOfBitRate = "bps"

const UnitOfBitRateGbps UnitOfBitRate = "Gbps"

const UnitOfBitRateKbps UnitOfBitRate = "kbps"

const UnitOfBitRateMbps UnitOfBitRate = "Mbps"

type UnitOfConditionValue string

const UnitOfConditionValueMillisecond UnitOfConditionValue = "Millisecond"

const UnitOfConditionValueMinute UnitOfConditionValue = "Minute"

const UnitOfConditionValuePercent UnitOfConditionValue = "Percent"

const UnitOfConditionValuePixel UnitOfConditionValue = "Pixel"

const UnitOfConditionValueSecond UnitOfConditionValue = "Second"

type UnitOfExtent string

const UnitOfExtentCm UnitOfExtent = "cm"

const UnitOfExtentInch UnitOfExtent = "Inch"

const UnitOfExtentMm UnitOfExtent = "mm"

const UnitOfExtentPercentofscreen UnitOfExtent = "PercentOfScreen"

const UnitOfExtentPixel UnitOfExtent = "Pixel"

type UnitOfFrameRate string

const UnitOfFrameRateHzinterlaced UnitOfFrameRate = "Hz(interlaced)"

const UnitOfFrameRateHznonInterlaced UnitOfFrameRate = "Hz(non-interlaced)"

type UnitOfFrequency string

const UnitOfFrequencyGhz UnitOfFrequency = "GHz"

const UnitOfFrequencyHz UnitOfFrequency = "Hz"

const UnitOfFrequencyKhz UnitOfFrequency = "kHz"

const UnitOfFrequencyMhz UnitOfFrequency = "MHz"

type UpdateIndicator string

const UpdateIndicatorOriginalmessage UpdateIndicator = "OriginalMessage"

const UpdateIndicatorUpdatemessage UpdateIndicator = "UpdateMessage"

type UseType string

const UseTypeAspercontract UseType = "AsPerContract"

const UseTypeBroadcast UseType = "Broadcast"

const UseTypeConditionaldownload UseType = "ConditionalDownload"

const UseTypeContentinfluencedstream UseType = "ContentInfluencedStream"

const UseTypeDisplay UseType = "Display"

const UseTypeDownload UseType = "Download"

const UseTypeKioskdownload UseType = "KioskDownload"

const UseTypeNarrowcast UseType = "Narrowcast"

const UseTypeNoninteractivestream UseType = "NonInteractiveStream"

const UseTypeOndemandstream UseType = "OnDemandStream"

const UseTypePerforminpublic UseType = "PerformInPublic"

const UseTypePermanentdownload UseType = "PermanentDownload"

const UseTypePlayback UseType = "Playback"

const UseTypePlayinpublic UseType = "PlayInPublic"

const UseTypePodcast UseType = "Podcast"

const UseTypePrint UseType = "Print"

const UseTypePrivatecopy UseType = "PrivateCopy"

const UseTypePurchaseasphysicalproduct UseType = "PurchaseAsPhysicalProduct"

const UseTypeRent UseType = "Rent"

const UseTypeSimulcast UseType = "Simulcast"

const UseTypeStream UseType = "Stream"

const UseTypeTethereddownload UseType = "TetheredDownload"

const UseTypeTimeinfluencedstream UseType = "TimeInfluencedStream"

const UseTypeUnknown UseType = "Unknown"

const UseTypeUseasalerttone UseType = "UseAsAlertTone"

const UseTypeUseasdevice UseType = "UseAsDevice"

const UseTypeUseaskaraoke UseType = "UseAsKaraoke"

const UseTypeUseasringbacktone UseType = "UseAsRingbackTone"

const UseTypeUseasringbacktune UseType = "UseAsRingbackTune"

const UseTypeUseasringtone UseType = "UseAsRingtone"

const UseTypeUseasringtune UseType = "UseAsRingtune"

const UseTypeUseasscreensaver UseType = "UseAsScreensaver"

const UseTypeUseasvoicemail UseType = "UseAsVoiceMail"

const UseTypeUserdefined UseType = "UserDefined"

const UseTypeUsermakeavailablelabelprovided UseType = "UserMakeAvailableLabelProvided"

const UseTypeUsermakeavailableuserprovided UseType = "UserMakeAvailableUserProvided"

const UseTypeWebcast UseType = "Webcast"

type UserInterfaceType string

const UserInterfaceTypeAspercontract UserInterfaceType = "AsPerContract"

const UserInterfaceTypeConnecteddevice UserInterfaceType = "ConnectedDevice"

const UserInterfaceTypeGameconsole UserInterfaceType = "GameConsole"

const UserInterfaceTypeJukebox UserInterfaceType = "Jukebox"

const UserInterfaceTypeKaraokemachine UserInterfaceType = "KaraokeMachine"

const UserInterfaceTypeKiosk UserInterfaceType = "Kiosk"

const UserInterfaceTypeLocalstoragejukebox UserInterfaceType = "LocalStorageJukebox"

const UserInterfaceTypePersonalcomputer UserInterfaceType = "PersonalComputer"

const UserInterfaceTypePhysicalmediawriter UserInterfaceType = "PhysicalMediaWriter"

const UserInterfaceTypePortabledevice UserInterfaceType = "PortableDevice"

const UserInterfaceTypeRemotestoragejukebox UserInterfaceType = "RemoteStorageJukebox"

const UserInterfaceTypeUnknown UserInterfaceType = "Unknown"

const UserInterfaceTypeUserdefined UserInterfaceType = "UserDefined"

type ValueType string

const ValueTypeCalculated ValueType = "Calculated"

const ValueTypeMaximum ValueType = "Maximum"

const ValueTypeMinimum ValueType = "Minimum"

type VideoCodecType string

const VideoCodecTypeAvc VideoCodecType = "AVC"

const VideoCodecTypeH261 VideoCodecType = "H.261"

const VideoCodecTypeH263 VideoCodecType = "H.263"

const VideoCodecTypeMpeg1 VideoCodecType = "MPEG-1"

const VideoCodecTypeMpeg2 VideoCodecType = "MPEG-2"

const VideoCodecTypeMpeg4 VideoCodecType = "MPEG-4"

const VideoCodecTypeQuicktime VideoCodecType = "QuickTime"

const VideoCodecTypeRealvideo VideoCodecType = "RealVideo"

const VideoCodecTypeShockwave VideoCodecType = "Shockwave"

const VideoCodecTypeUnknown VideoCodecType = "Unknown"

const VideoCodecTypeUserdefined VideoCodecType = "UserDefined"

const VideoCodecTypeWmv VideoCodecType = "WMV"

type VideoDefinitionType string

const VideoDefinitionTypeHighdefinition VideoDefinitionType = "HighDefinition"

const VideoDefinitionTypeStandarddefinition VideoDefinitionType = "StandardDefinition"

type VideoType string

const VideoTypeAdvertisementvideo VideoType = "AdvertisementVideo"

const VideoTypeAnimation VideoType = "Animation"

const VideoTypeConcertclip VideoType = "ConcertClip"

const VideoTypeConcertvideo VideoType = "ConcertVideo"

const VideoTypeCorporatefilm VideoType = "CorporateFilm"

const VideoTypeDocumentary VideoType = "Documentary"

const VideoTypeEpisode VideoType = "Episode"

const VideoTypeFeaturefilm VideoType = "FeatureFilm"

const VideoTypeInfomercialvideo VideoType = "InfomercialVideo"

const VideoTypeKaraoke VideoType = "Karaoke"

const VideoTypeLiveeventvideo VideoType = "LiveEventVideo"

const VideoTypeLongformmusicalworkvideo VideoType = "LongFormMusicalWorkVideo"

const VideoTypeLongformnonmusicalworkvideo VideoType = "LongFormNonMusicalWorkVideo"

const VideoTypeMenu VideoType = "Menu"

const VideoTypeMusicalworkclip VideoType = "MusicalWorkClip"

const VideoTypeMusicalworkreadalongvideo VideoType = "MusicalWorkReadalongVideo"

const VideoTypeMusicalworktrailer VideoType = "MusicalWorkTrailer"

const VideoTypeMusicalworkvideochapter VideoType = "MusicalWorkVideoChapter"

const VideoTypeNews VideoType = "News"

const VideoTypeNonmusicalworkclip VideoType = "NonMusicalWorkClip"

const VideoTypeNonmusicalworkreadalongvideo VideoType = "NonMusicalWorkReadalongVideo"

const VideoTypeNonmusicalworktrailer VideoType = "NonMusicalWorkTrailer"

const VideoTypeNonmusicalworkvideochapter VideoType = "NonMusicalWorkVideoChapter"

const VideoTypeNonserialaudiovisualrecording VideoType = "NonSerialAudioVisualRecording"

const VideoTypeSeason VideoType = "Season"

const VideoTypeSeries VideoType = "Series"

const VideoTypeShortformmusicalworkvideo VideoType = "ShortFormMusicalWorkVideo"

const VideoTypeShortformnonmusicalworkvideo VideoType = "ShortFormNonMusicalWorkVideo"

const VideoTypeTrailervideo VideoType = "TrailerVideo"

const VideoTypeUnknown VideoType = "Unknown"

const VideoTypeUserdefined VideoType = "UserDefined"

const VideoTypeVideochapter VideoType = "VideoChapter"

type VisualPerceptionType string

const VisualPerceptionTypeBackground VisualPerceptionType = "Background"

const VisualPerceptionTypeUserdefined VisualPerceptionType = "UserDefined"

const VisualPerceptionTypeVisual VisualPerceptionType = "Visual"

type VocalType string

const VocalTypeInstrumental VocalType = "Instrumental"

const VocalTypeUserdefined VocalType = "UserDefined"

const VocalTypeVocal VocalType = "Vocal"

type WsMessageStatus string

const WsMessageStatusBackendprocessingerror WsMessageStatus = "BackendProcessingError"

const WsMessageStatusNovalidmessagereceived WsMessageStatus = "NoValidMessageReceived"

const WsMessageStatusValidmessagequeuedforprocessing WsMessageStatus = "ValidMessageQueuedForProcessing"

const WsMessageStatusValidmessagereceived WsMessageStatus = "ValidMessageReceived"

type LocalCollectionAnchorReference string

type LocalResourceAnchorReference string
