// Code generated by https://github.com/gocomply/xsd2go; DO NOT EDIT.
// Models for http://ddex.net/xml/20121219/iso4217a
package iso4217a

import ()

// XSD ComplexType declarations

// XSD SimpleType declarations

type CurrencyCode string

const CurrencyCodeAed CurrencyCode = "AED"

const CurrencyCodeAfn CurrencyCode = "AFN"

const CurrencyCodeAll CurrencyCode = "ALL"

const CurrencyCodeAmd CurrencyCode = "AMD"

const CurrencyCodeAng CurrencyCode = "ANG"

const CurrencyCodeAoa CurrencyCode = "AOA"

const CurrencyCodeArs CurrencyCode = "ARS"

const CurrencyCodeAud CurrencyCode = "AUD"

const CurrencyCodeAwg CurrencyCode = "AWG"

const CurrencyCodeAzn CurrencyCode = "AZN"

const CurrencyCodeBam CurrencyCode = "BAM"

const CurrencyCodeBbd CurrencyCode = "BBD"

const CurrencyCodeBdt CurrencyCode = "BDT"

const CurrencyCodeBgn CurrencyCode = "BGN"

const CurrencyCodeBhd CurrencyCode = "BHD"

const CurrencyCodeBif CurrencyCode = "BIF"

const CurrencyCodeBmd CurrencyCode = "BMD"

const CurrencyCodeBnd CurrencyCode = "BND"

const CurrencyCodeBob CurrencyCode = "BOB"

const CurrencyCodeBov CurrencyCode = "BOV"

const CurrencyCodeBrl CurrencyCode = "BRL"

const CurrencyCodeBsd CurrencyCode = "BSD"

const CurrencyCodeBtn CurrencyCode = "BTN"

const CurrencyCodeBwp CurrencyCode = "BWP"

const CurrencyCodeByr CurrencyCode = "BYR"

const CurrencyCodeBzd CurrencyCode = "BZD"

const CurrencyCodeCad CurrencyCode = "CAD"

const CurrencyCodeCdf CurrencyCode = "CDF"

const CurrencyCodeChf CurrencyCode = "CHF"

const CurrencyCodeClf CurrencyCode = "CLF"

const CurrencyCodeClp CurrencyCode = "CLP"

const CurrencyCodeCny CurrencyCode = "CNY"

const CurrencyCodeCop CurrencyCode = "COP"

const CurrencyCodeCou CurrencyCode = "COU"

const CurrencyCodeCrc CurrencyCode = "CRC"

const CurrencyCodeCuc CurrencyCode = "CUC"

const CurrencyCodeCup CurrencyCode = "CUP"

const CurrencyCodeCve CurrencyCode = "CVE"

const CurrencyCodeCzk CurrencyCode = "CZK"

const CurrencyCodeDjf CurrencyCode = "DJF"

const CurrencyCodeDkk CurrencyCode = "DKK"

const CurrencyCodeDop CurrencyCode = "DOP"

const CurrencyCodeDzd CurrencyCode = "DZD"

const CurrencyCodeEgp CurrencyCode = "EGP"

const CurrencyCodeErn CurrencyCode = "ERN"

const CurrencyCodeEtb CurrencyCode = "ETB"

const CurrencyCodeEur CurrencyCode = "EUR"

const CurrencyCodeFjd CurrencyCode = "FJD"

const CurrencyCodeFkp CurrencyCode = "FKP"

const CurrencyCodeGbp CurrencyCode = "GBP"

const CurrencyCodeGel CurrencyCode = "GEL"

const CurrencyCodeGhs CurrencyCode = "GHS"

const CurrencyCodeGip CurrencyCode = "GIP"

const CurrencyCodeGmd CurrencyCode = "GMD"

const CurrencyCodeGnf CurrencyCode = "GNF"

const CurrencyCodeGtq CurrencyCode = "GTQ"

const CurrencyCodeGyd CurrencyCode = "GYD"

const CurrencyCodeHkd CurrencyCode = "HKD"

const CurrencyCodeHnl CurrencyCode = "HNL"

const CurrencyCodeHrk CurrencyCode = "HRK"

const CurrencyCodeHtg CurrencyCode = "HTG"

const CurrencyCodeHuf CurrencyCode = "HUF"

const CurrencyCodeIdr CurrencyCode = "IDR"

const CurrencyCodeIls CurrencyCode = "ILS"

const CurrencyCodeInr CurrencyCode = "INR"

const CurrencyCodeIqd CurrencyCode = "IQD"

const CurrencyCodeIrr CurrencyCode = "IRR"

const CurrencyCodeIsk CurrencyCode = "ISK"

const CurrencyCodeJmd CurrencyCode = "JMD"

const CurrencyCodeJod CurrencyCode = "JOD"

const CurrencyCodeJpy CurrencyCode = "JPY"

const CurrencyCodeKes CurrencyCode = "KES"

const CurrencyCodeKgs CurrencyCode = "KGS"

const CurrencyCodeKhr CurrencyCode = "KHR"

const CurrencyCodeKmf CurrencyCode = "KMF"

const CurrencyCodeKpw CurrencyCode = "KPW"

const CurrencyCodeKrw CurrencyCode = "KRW"

const CurrencyCodeKwd CurrencyCode = "KWD"

const CurrencyCodeKyd CurrencyCode = "KYD"

const CurrencyCodeKzt CurrencyCode = "KZT"

const CurrencyCodeLak CurrencyCode = "LAK"

const CurrencyCodeLbp CurrencyCode = "LBP"

const CurrencyCodeLkr CurrencyCode = "LKR"

const CurrencyCodeLrd CurrencyCode = "LRD"

const CurrencyCodeLsl CurrencyCode = "LSL"

const CurrencyCodeLtl CurrencyCode = "LTL"

const CurrencyCodeLvl CurrencyCode = "LVL"

const CurrencyCodeLyd CurrencyCode = "LYD"

const CurrencyCodeMad CurrencyCode = "MAD"

const CurrencyCodeMdl CurrencyCode = "MDL"

const CurrencyCodeMga CurrencyCode = "MGA"

const CurrencyCodeMkd CurrencyCode = "MKD"

const CurrencyCodeMmk CurrencyCode = "MMK"

const CurrencyCodeMnt CurrencyCode = "MNT"

const CurrencyCodeMop CurrencyCode = "MOP"

const CurrencyCodeMro CurrencyCode = "MRO"

const CurrencyCodeMur CurrencyCode = "MUR"

const CurrencyCodeMvr CurrencyCode = "MVR"

const CurrencyCodeMwk CurrencyCode = "MWK"

const CurrencyCodeMxn CurrencyCode = "MXN"

const CurrencyCodeMxv CurrencyCode = "MXV"

const CurrencyCodeMyr CurrencyCode = "MYR"

const CurrencyCodeMzm CurrencyCode = "MZM"

const CurrencyCodeNad CurrencyCode = "NAD"

const CurrencyCodeNgn CurrencyCode = "NGN"

const CurrencyCodeNio CurrencyCode = "NIO"

const CurrencyCodeNok CurrencyCode = "NOK"

const CurrencyCodeNpr CurrencyCode = "NPR"

const CurrencyCodeNzd CurrencyCode = "NZD"

const CurrencyCodeOmr CurrencyCode = "OMR"

const CurrencyCodePab CurrencyCode = "PAB"

const CurrencyCodePen CurrencyCode = "PEN"

const CurrencyCodePgk CurrencyCode = "PGK"

const CurrencyCodePhp CurrencyCode = "PHP"

const CurrencyCodePkr CurrencyCode = "PKR"

const CurrencyCodePln CurrencyCode = "PLN"

const CurrencyCodePyg CurrencyCode = "PYG"

const CurrencyCodeQar CurrencyCode = "QAR"

const CurrencyCodeRon CurrencyCode = "RON"

const CurrencyCodeRsd CurrencyCode = "RSD"

const CurrencyCodeRub CurrencyCode = "RUB"

const CurrencyCodeRwf CurrencyCode = "RWF"

const CurrencyCodeSar CurrencyCode = "SAR"

const CurrencyCodeSbd CurrencyCode = "SBD"

const CurrencyCodeScr CurrencyCode = "SCR"

const CurrencyCodeSdg CurrencyCode = "SDG"

const CurrencyCodeSek CurrencyCode = "SEK"

const CurrencyCodeSgd CurrencyCode = "SGD"

const CurrencyCodeShp CurrencyCode = "SHP"

const CurrencyCodeSll CurrencyCode = "SLL"

const CurrencyCodeSos CurrencyCode = "SOS"

const CurrencyCodeSrd CurrencyCode = "SRD"

const CurrencyCodeStd CurrencyCode = "STD"

const CurrencyCodeSvc CurrencyCode = "SVC"

const CurrencyCodeSyp CurrencyCode = "SYP"

const CurrencyCodeSzl CurrencyCode = "SZL"

const CurrencyCodeThb CurrencyCode = "THB"

const CurrencyCodeTjs CurrencyCode = "TJS"

const CurrencyCodeTmt CurrencyCode = "TMT"

const CurrencyCodeTnd CurrencyCode = "TND"

const CurrencyCodeTop CurrencyCode = "TOP"

const CurrencyCodeTry CurrencyCode = "TRY"

const CurrencyCodeTtd CurrencyCode = "TTD"

const CurrencyCodeTwd CurrencyCode = "TWD"

const CurrencyCodeTzs CurrencyCode = "TZS"

const CurrencyCodeUah CurrencyCode = "UAH"

const CurrencyCodeUgx CurrencyCode = "UGX"

const CurrencyCodeUsd CurrencyCode = "USD"

const CurrencyCodeUyi CurrencyCode = "UYI"

const CurrencyCodeUyu CurrencyCode = "UYU"

const CurrencyCodeUzs CurrencyCode = "UZS"

const CurrencyCodeVef CurrencyCode = "VEF"

const CurrencyCodeVnd CurrencyCode = "VND"

const CurrencyCodeVuv CurrencyCode = "VUV"

const CurrencyCodeWst CurrencyCode = "WST"

const CurrencyCodeXaf CurrencyCode = "XAF"

const CurrencyCodeXcd CurrencyCode = "XCD"

const CurrencyCodeXof CurrencyCode = "XOF"

const CurrencyCodeXpf CurrencyCode = "XPF"

const CurrencyCodeYer CurrencyCode = "YER"

const CurrencyCodeZar CurrencyCode = "ZAR"

const CurrencyCodeZmk CurrencyCode = "ZMK"

const CurrencyCodeZwl CurrencyCode = "ZWL"
