// Code generated by https://github.com/gocomply/xsd2go; DO NOT EDIT.
// Models for http://ddex.net/xml/20121219/iso3166a2
package iso3166a2

import ()

// XSD ComplexType declarations

// XSD SimpleType declarations

type TerritoryCode string

const TerritoryCodeAd TerritoryCode = "AD"

const TerritoryCodeAe TerritoryCode = "AE"

const TerritoryCodeAf TerritoryCode = "AF"

const TerritoryCodeAg TerritoryCode = "AG"

const TerritoryCodeAi TerritoryCode = "AI"

const TerritoryCodeAl TerritoryCode = "AL"

const TerritoryCodeAm TerritoryCode = "AM"

const TerritoryCodeAn TerritoryCode = "AN"

const TerritoryCodeAo TerritoryCode = "AO"

const TerritoryCodeAq TerritoryCode = "AQ"

const TerritoryCodeAr TerritoryCode = "AR"

const TerritoryCodeAs TerritoryCode = "AS"

const TerritoryCodeAt TerritoryCode = "AT"

const TerritoryCodeAu TerritoryCode = "AU"

const TerritoryCodeAw TerritoryCode = "AW"

const TerritoryCodeAx TerritoryCode = "AX"

const TerritoryCodeAz TerritoryCode = "AZ"

const TerritoryCodeBa TerritoryCode = "BA"

const TerritoryCodeBb TerritoryCode = "BB"

const TerritoryCodeBd TerritoryCode = "BD"

const TerritoryCodeBe TerritoryCode = "BE"

const TerritoryCodeBf TerritoryCode = "BF"

const TerritoryCodeBg TerritoryCode = "BG"

const TerritoryCodeBh TerritoryCode = "BH"

const TerritoryCodeBi TerritoryCode = "BI"

const TerritoryCodeBj TerritoryCode = "BJ"

const TerritoryCodeBl TerritoryCode = "BL"

const TerritoryCodeBm TerritoryCode = "BM"

const TerritoryCodeBn TerritoryCode = "BN"

const TerritoryCodeBo TerritoryCode = "BO"

const TerritoryCodeBq TerritoryCode = "BQ"

const TerritoryCodeBr TerritoryCode = "BR"

const TerritoryCodeBs TerritoryCode = "BS"

const TerritoryCodeBt TerritoryCode = "BT"

const TerritoryCodeBv TerritoryCode = "BV"

const TerritoryCodeBw TerritoryCode = "BW"

const TerritoryCodeBy TerritoryCode = "BY"

const TerritoryCodeBz TerritoryCode = "BZ"

const TerritoryCodeCa TerritoryCode = "CA"

const TerritoryCodeCc TerritoryCode = "CC"

const TerritoryCodeCd TerritoryCode = "CD"

const TerritoryCodeCf TerritoryCode = "CF"

const TerritoryCodeCg TerritoryCode = "CG"

const TerritoryCodeCh TerritoryCode = "CH"

const TerritoryCodeCi TerritoryCode = "CI"

const TerritoryCodeCk TerritoryCode = "CK"

const TerritoryCodeCl TerritoryCode = "CL"

const TerritoryCodeCm TerritoryCode = "CM"

const TerritoryCodeCn TerritoryCode = "CN"

const TerritoryCodeCo TerritoryCode = "CO"

const TerritoryCodeCr TerritoryCode = "CR"

const TerritoryCodeCs TerritoryCode = "CS"

const TerritoryCodeCu TerritoryCode = "CU"

const TerritoryCodeCv TerritoryCode = "CV"

const TerritoryCodeCw TerritoryCode = "CW"

const TerritoryCodeCx TerritoryCode = "CX"

const TerritoryCodeCy TerritoryCode = "CY"

const TerritoryCodeCz TerritoryCode = "CZ"

const TerritoryCodeDe TerritoryCode = "DE"

const TerritoryCodeDj TerritoryCode = "DJ"

const TerritoryCodeDk TerritoryCode = "DK"

const TerritoryCodeDm TerritoryCode = "DM"

const TerritoryCodeDo TerritoryCode = "DO"

const TerritoryCodeDz TerritoryCode = "DZ"

const TerritoryCodeEc TerritoryCode = "EC"

const TerritoryCodeEe TerritoryCode = "EE"

const TerritoryCodeEg TerritoryCode = "EG"

const TerritoryCodeEh TerritoryCode = "EH"

const TerritoryCodeEr TerritoryCode = "ER"

const TerritoryCodeEs TerritoryCode = "ES"

const TerritoryCodeEt TerritoryCode = "ET"

const TerritoryCodeFi TerritoryCode = "FI"

const TerritoryCodeFj TerritoryCode = "FJ"

const TerritoryCodeFk TerritoryCode = "FK"

const TerritoryCodeFm TerritoryCode = "FM"

const TerritoryCodeFo TerritoryCode = "FO"

const TerritoryCodeFr TerritoryCode = "FR"

const TerritoryCodeGa TerritoryCode = "GA"

const TerritoryCodeGb TerritoryCode = "GB"

const TerritoryCodeGd TerritoryCode = "GD"

const TerritoryCodeGe TerritoryCode = "GE"

const TerritoryCodeGf TerritoryCode = "GF"

const TerritoryCodeGg TerritoryCode = "GG"

const TerritoryCodeGh TerritoryCode = "GH"

const TerritoryCodeGi TerritoryCode = "GI"

const TerritoryCodeGl TerritoryCode = "GL"

const TerritoryCodeGm TerritoryCode = "GM"

const TerritoryCodeGn TerritoryCode = "GN"

const TerritoryCodeGp TerritoryCode = "GP"

const TerritoryCodeGq TerritoryCode = "GQ"

const TerritoryCodeGr TerritoryCode = "GR"

const TerritoryCodeGs TerritoryCode = "GS"

const TerritoryCodeGt TerritoryCode = "GT"

const TerritoryCodeGu TerritoryCode = "GU"

const TerritoryCodeGw TerritoryCode = "GW"

const TerritoryCodeGy TerritoryCode = "GY"

const TerritoryCodeHk TerritoryCode = "HK"

const TerritoryCodeHm TerritoryCode = "HM"

const TerritoryCodeHn TerritoryCode = "HN"

const TerritoryCodeHr TerritoryCode = "HR"

const TerritoryCodeHt TerritoryCode = "HT"

const TerritoryCodeHu TerritoryCode = "HU"

const TerritoryCodeId TerritoryCode = "ID"

const TerritoryCodeIe TerritoryCode = "IE"

const TerritoryCodeIl TerritoryCode = "IL"

const TerritoryCodeIm TerritoryCode = "IM"

const TerritoryCodeIn TerritoryCode = "IN"

const TerritoryCodeIo TerritoryCode = "IO"

const TerritoryCodeIq TerritoryCode = "IQ"

const TerritoryCodeIr TerritoryCode = "IR"

const TerritoryCodeIs TerritoryCode = "IS"

const TerritoryCodeIt TerritoryCode = "IT"

const TerritoryCodeJe TerritoryCode = "JE"

const TerritoryCodeJm TerritoryCode = "JM"

const TerritoryCodeJo TerritoryCode = "JO"

const TerritoryCodeJp TerritoryCode = "JP"

const TerritoryCodeKe TerritoryCode = "KE"

const TerritoryCodeKg TerritoryCode = "KG"

const TerritoryCodeKh TerritoryCode = "KH"

const TerritoryCodeKi TerritoryCode = "KI"

const TerritoryCodeKm TerritoryCode = "KM"

const TerritoryCodeKn TerritoryCode = "KN"

const TerritoryCodeKp TerritoryCode = "KP"

const TerritoryCodeKr TerritoryCode = "KR"

const TerritoryCodeKw TerritoryCode = "KW"

const TerritoryCodeKy TerritoryCode = "KY"

const TerritoryCodeKz TerritoryCode = "KZ"

const TerritoryCodeLa TerritoryCode = "LA"

const TerritoryCodeLb TerritoryCode = "LB"

const TerritoryCodeLc TerritoryCode = "LC"

const TerritoryCodeLi TerritoryCode = "LI"

const TerritoryCodeLk TerritoryCode = "LK"

const TerritoryCodeLr TerritoryCode = "LR"

const TerritoryCodeLs TerritoryCode = "LS"

const TerritoryCodeLt TerritoryCode = "LT"

const TerritoryCodeLu TerritoryCode = "LU"

const TerritoryCodeLv TerritoryCode = "LV"

const TerritoryCodeLy TerritoryCode = "LY"

const TerritoryCodeMa TerritoryCode = "MA"

const TerritoryCodeMc TerritoryCode = "MC"

const TerritoryCodeMd TerritoryCode = "MD"

const TerritoryCodeMe TerritoryCode = "ME"

const TerritoryCodeMf TerritoryCode = "MF"

const TerritoryCodeMg TerritoryCode = "MG"

const TerritoryCodeMh TerritoryCode = "MH"

const TerritoryCodeMk TerritoryCode = "MK"

const TerritoryCodeMl TerritoryCode = "ML"

const TerritoryCodeMm TerritoryCode = "MM"

const TerritoryCodeMn TerritoryCode = "MN"

const TerritoryCodeMo TerritoryCode = "MO"

const TerritoryCodeMp TerritoryCode = "MP"

const TerritoryCodeMq TerritoryCode = "MQ"

const TerritoryCodeMr TerritoryCode = "MR"

const TerritoryCodeMs TerritoryCode = "MS"

const TerritoryCodeMt TerritoryCode = "MT"

const TerritoryCodeMu TerritoryCode = "MU"

const TerritoryCodeMv TerritoryCode = "MV"

const TerritoryCodeMw TerritoryCode = "MW"

const TerritoryCodeMx TerritoryCode = "MX"

const TerritoryCodeMy TerritoryCode = "MY"

const TerritoryCodeMz TerritoryCode = "MZ"

const TerritoryCodeNa TerritoryCode = "NA"

const TerritoryCodeNc TerritoryCode = "NC"

const TerritoryCodeNe TerritoryCode = "NE"

const TerritoryCodeNf TerritoryCode = "NF"

const TerritoryCodeNg TerritoryCode = "NG"

const TerritoryCodeNi TerritoryCode = "NI"

const TerritoryCodeNl TerritoryCode = "NL"

const TerritoryCodeNo TerritoryCode = "NO"

const TerritoryCodeNp TerritoryCode = "NP"

const TerritoryCodeNr TerritoryCode = "NR"

const TerritoryCodeNu TerritoryCode = "NU"

const TerritoryCodeNz TerritoryCode = "NZ"

const TerritoryCodeOm TerritoryCode = "OM"

const TerritoryCodePa TerritoryCode = "PA"

const TerritoryCodePe TerritoryCode = "PE"

const TerritoryCodePf TerritoryCode = "PF"

const TerritoryCodePg TerritoryCode = "PG"

const TerritoryCodePh TerritoryCode = "PH"

const TerritoryCodePk TerritoryCode = "PK"

const TerritoryCodePl TerritoryCode = "PL"

const TerritoryCodePm TerritoryCode = "PM"

const TerritoryCodePn TerritoryCode = "PN"

const TerritoryCodePr TerritoryCode = "PR"

const TerritoryCodePs TerritoryCode = "PS"

const TerritoryCodePt TerritoryCode = "PT"

const TerritoryCodePw TerritoryCode = "PW"

const TerritoryCodePy TerritoryCode = "PY"

const TerritoryCodeQa TerritoryCode = "QA"

const TerritoryCodeRe TerritoryCode = "RE"

const TerritoryCodeRo TerritoryCode = "RO"

const TerritoryCodeRs TerritoryCode = "RS"

const TerritoryCodeRu TerritoryCode = "RU"

const TerritoryCodeRw TerritoryCode = "RW"

const TerritoryCodeSa TerritoryCode = "SA"

const TerritoryCodeSb TerritoryCode = "SB"

const TerritoryCodeSc TerritoryCode = "SC"

const TerritoryCodeSd TerritoryCode = "SD"

const TerritoryCodeSe TerritoryCode = "SE"

const TerritoryCodeSg TerritoryCode = "SG"

const TerritoryCodeSh TerritoryCode = "SH"

const TerritoryCodeSi TerritoryCode = "SI"

const TerritoryCodeSj TerritoryCode = "SJ"

const TerritoryCodeSk TerritoryCode = "SK"

const TerritoryCodeSl TerritoryCode = "SL"

const TerritoryCodeSm TerritoryCode = "SM"

const TerritoryCodeSn TerritoryCode = "SN"

const TerritoryCodeSo TerritoryCode = "SO"

const TerritoryCodeSr TerritoryCode = "SR"

const TerritoryCodeSs TerritoryCode = "SS"

const TerritoryCodeSt TerritoryCode = "ST"

const TerritoryCodeSv TerritoryCode = "SV"

const TerritoryCodeSx TerritoryCode = "SX"

const TerritoryCodeSy TerritoryCode = "SY"

const TerritoryCodeSz TerritoryCode = "SZ"

const TerritoryCodeTc TerritoryCode = "TC"

const TerritoryCodeTd TerritoryCode = "TD"

const TerritoryCodeTf TerritoryCode = "TF"

const TerritoryCodeTg TerritoryCode = "TG"

const TerritoryCodeTh TerritoryCode = "TH"

const TerritoryCodeTj TerritoryCode = "TJ"

const TerritoryCodeTk TerritoryCode = "TK"

const TerritoryCodeTl TerritoryCode = "TL"

const TerritoryCodeTm TerritoryCode = "TM"

const TerritoryCodeTn TerritoryCode = "TN"

const TerritoryCodeTo TerritoryCode = "TO"

const TerritoryCodeTr TerritoryCode = "TR"

const TerritoryCodeTt TerritoryCode = "TT"

const TerritoryCodeTv TerritoryCode = "TV"

const TerritoryCodeTw TerritoryCode = "TW"

const TerritoryCodeTz TerritoryCode = "TZ"

const TerritoryCodeUa TerritoryCode = "UA"

const TerritoryCodeUg TerritoryCode = "UG"

const TerritoryCodeUm TerritoryCode = "UM"

const TerritoryCodeUs TerritoryCode = "US"

const TerritoryCodeUy TerritoryCode = "UY"

const TerritoryCodeUz TerritoryCode = "UZ"

const TerritoryCodeVa TerritoryCode = "VA"

const TerritoryCodeVc TerritoryCode = "VC"

const TerritoryCodeVe TerritoryCode = "VE"

const TerritoryCodeVg TerritoryCode = "VG"

const TerritoryCodeVi TerritoryCode = "VI"

const TerritoryCodeVn TerritoryCode = "VN"

const TerritoryCodeVu TerritoryCode = "VU"

const TerritoryCodeWf TerritoryCode = "WF"

const TerritoryCodeWs TerritoryCode = "WS"

const TerritoryCodeYe TerritoryCode = "YE"

const TerritoryCodeYt TerritoryCode = "YT"

const TerritoryCodeZa TerritoryCode = "ZA"

const TerritoryCodeZm TerritoryCode = "ZM"

const TerritoryCodeZw TerritoryCode = "ZW"
